export interface PainPointPage {
  slug: string
  label: string
  h1: string
  metaDescription: string
  bullets: string[]
  forYou: string[]
  notForYou: string[]
  faqs: { question: string; answer: string }[]
}

export const painPoints: PainPointPage[] = [
  {
    slug: 'founder-bottleneck',
    label: 'Founder Bottleneck',
    h1: 'Stuck as the Bottleneck in Your Own Business? Here Is the Fix',
    metaDescription: 'If every deliverable runs through you personally, you are not running a business. You are creating a job. Client Intelligence breaks the founder bottleneck by encoding your Frameworks in the Account Brain.',
    bullets: [
      'Every client deliverable requires your personal touch before it goes out',
      'Your team asks you to make every meaningful decision',
      'When you are unavailable, client work stops entirely',
      'You hired people but still do most of the real work yourself',
      'Your calendar is full but your revenue is not growing',
      'You are working more hours than you did as a freelancer',
    ],
    forYou: [
      'You serve multiple clients and cannot personally deliver to all of them at once',
      'You have Frameworks and methodology worth encoding in the Account Brain',
      'You want to grow revenue without proportionally growing your personal hours',
      'You are ready to trust systems over your constant presence',
    ],
    notForYou: [
      'You prefer to be personally involved in every client touchpoint',
      'You only serve one client at a time and want to keep it that way',
      'You are not willing to encode your methodology into the Account Brain',
    ],
    faqs: [
      { question: 'What actually creates the founder bottleneck?', answer: 'The bottleneck forms when your expertise lives only in your head. Every decision and deliverable requires you because there is no system that applies your judgment without you present. Client Intelligence breaks this by encoding your Frameworks in the Account Brain so they operate without your constant involvement.' },
      { question: 'Will systematizing reduce the quality clients pay for?', answer: 'Only if quality depends on your personal presence rather than your methodology. When your Frameworks are encoded in the Account Brain correctly, Intelligence applies them consistently, often with more thoroughness than your manual delivery under time pressure.' },
      { question: 'How long does it take to break the bottleneck?', answer: 'Most users see meaningful change within 30 to 60 days. The first phase is Framework encoding in the Account Brain. The second is client Workspace setup. By 60 days, a significant portion of delivery runs without your direct involvement.' },
      { question: 'What if I do not trust AI to represent my work?', answer: 'You do not have to trust it blindly. Start with lower-stakes deliverables and review Intelligence outputs until you are confident. Most users move to reviewing final outputs only within the first few weeks.' },
    ],
  },
  {
    slug: 'too-busy-to-scale',
    label: 'Too Busy to Scale',
    h1: 'Too Busy to Grow Your Service Business? This Is Why',
    metaDescription: 'Busy is not the problem. Systems are. If you are too busy to take on more clients, Client Intelligence replaces the time bottleneck by encoding your methodology in the Account Brain and running delivery from client Workspaces.',
    bullets: [
      'You turn away referrals every month because you have no capacity',
      'Every new client would require you to work hours you do not have',
      'Your days are full but your revenue ceiling feels fixed',
      'You have tried to delegate but quality falls apart without your involvement',
      'You are running the same hamster wheel at a higher speed every year',
      'You know you should build systems but cannot find time to build them while serving clients',
    ],
    forYou: [
      'You have real methodology worth encoding in the Account Brain',
      'You serve or want to serve multiple clients simultaneously',
      'You are willing to invest time upfront to build the systems that free you later',
      'You want to grow revenue without working more hours',
    ],
    notForYou: [
      'You are content at your current revenue and client volume',
      'You prefer a boutique practice where every client gets your full personal time',
      'You have not identified what specifically is consuming your time',
    ],
    faqs: [
      { question: 'Why am I too busy if I am good at what I do?', answer: 'Being good at your craft does not create time. It creates demand. The busier you get, the more critical systematic delivery becomes. Client Intelligence encodes your expertise in the Account Brain so demand does not require proportionally more of your time.' },
      { question: 'I am so busy I cannot even set up a new system. What do I do?', answer: 'Start with just one client Workspace and one Brain Dump session. Most users take 90 minutes to get functional. The time investment is front-loaded. The returns are ongoing.' },
      { question: 'Is the problem really time, or something else?', answer: 'Usually it is leverage, or the lack of it. Your expertise only exists in your head. Client Intelligence creates a parallel track where your methodology works through the Account Brain without requiring your time for every application.' },
      { question: 'How much time does Client Intelligence realistically save?', answer: 'Most users save 3 to 8 hours per week within 60 days, primarily on deliverable creation, client prep, and documentation. At $300 or more per hour billing rates, that is significant recovered capacity.' },
    ],
  },
  {
    slug: 'cant-take-on-more-clients',
    label: 'Can\'t Take On More Clients',
    h1: 'Why You Can\'t Take On More Clients (And How AI Solves It)',
    metaDescription: 'Turning away clients when demand exists is expensive. Client Intelligence increases your service capacity without adding headcount or working more hours.',
    bullets: [
      'You are at full capacity but turning away pre-qualified referrals every month',
      'Every new client would mean sacrificing quality for existing clients',
      'You have calculated that you would need to hire before you could grow, but margins do not support it',
      'Your capacity ceiling has been the same for two years',
      'The revenue you are leaving on the table is becoming impossible to ignore',
      'You know demand exists but you cannot capture it',
    ],
    forYou: [
      'You regularly receive referrals you have to turn down',
      'Your current clients are satisfied but your capacity is fully allocated',
      'You want to serve 30 to 100% more clients without proportional time increase',
      'You have repeatable delivery elements that could be encoded in the Account Brain',
    ],
    notForYou: [
      'Your service model requires intensive one-on-one time that genuinely cannot be systematized',
      'You are satisfied with your current client volume and revenue',
      'You do not have a methodology. Every engagement is purely bespoke.',
    ],
    faqs: [
      { question: 'Why can\'t I just hire to solve this?', answer: 'Hiring adds headcount costs, management overhead, and quality variability. For many service businesses, the economics only work above 15 to 20 clients per hire. Client Intelligence lets you scale the 5 to 15 client range without hiring.' },
      { question: 'What is the realistic capacity increase?', answer: 'Most users achieve 30 to 80% capacity increase within 60 days. The ceiling depends on how much of your delivery is systematizable. Highly Framework-driven practices scale faster.' },
      { question: 'Will existing clients suffer if I take on more?', answer: 'Only if quality depends on your personal time. When Intelligence runs delivery from the Account Brain, existing clients often receive more consistent service than before because the Framework never cuts corners under pressure.' },
      { question: 'How quickly can I onboard new clients once capacity increases?', answer: 'Onboarding with Client Intelligence is typically 50 to 70% faster than manual. You create a Workspace, run a Brain Dump session, and Intelligence has full context from the first working session.' },
    ],
  },
  {
    slug: 'client-data-mixing-ai',
    label: 'AI Mixing Client Data',
    h1: 'Is Your AI Mixing Client Data? Here\'s Why That\'s a Problem',
    metaDescription: 'Using ChatGPT or shared AI tools across multiple clients risks confidentiality. If your AI can reference one client data when working on another, you have a serious problem.',
    bullets: [
      'You use the same AI tool for multiple clients and cannot guarantee data separation',
      'AI outputs occasionally reference details that seem wrong for the current client',
      'You cannot honestly tell clients their data is isolated from other engagements',
      'Your NDAs require data separation you cannot currently demonstrate',
      'You have had a close call where AI surfaced the wrong client information',
      'You avoid using AI for sensitive client work entirely because of data risk',
    ],
    forYou: [
      'You serve multiple clients with confidential information',
      'Your contracts include data handling obligations',
      'You want to use AI freely without worrying about cross-client contamination',
      'You work in professional services where confidentiality is a baseline requirement',
    ],
    notForYou: [
      'You serve only one client and data mixing is impossible',
      'You do not use AI for any client work currently',
      'Your client engagements involve no confidential information',
    ],
    faqs: [
      { question: 'How does AI mix client data without me realizing it?', answer: 'In shared AI tools, context from previous sessions or shared projects can persist. If you paste Client A strategy doc in one session and Client B in the next, there is risk of contextual bleed, especially in tools that maintain conversation history.' },
      { question: 'Is this a real risk or a hypothetical one?', answer: 'It is real. Multiple professional services users have reported AI outputs that referenced the wrong client. Beyond incidents, the architectural risk exists whether or not you have experienced it yet.' },
      { question: 'How does Client Intelligence prevent data mixing?', answer: 'Workspace isolation is architectural. Each client Workspace is a separate, walled environment. When you work in Client A Workspace, Intelligence only has access to Client A data. Cross-contamination is structurally impossible.' },
      { question: 'Can I demonstrate isolation to clients who ask?', answer: 'Yes. The Workspace architecture is explainable and demonstrable. The structural nature of the isolation, not just policy, tends to satisfy technically sophisticated clients and legal reviewers.' },
    ],
  },
  {
    slug: 'repeating-yourself-every-client',
    label: 'Repeating Yourself to Every Client',
    h1: 'Stop Repeating Your Methodology to Every New Client',
    metaDescription: 'If you re-explain your Framework from scratch with every new client, you are burning your most valuable asset: your time. Client Intelligence encodes your methodology in the Account Brain once and applies it everywhere.',
    bullets: [
      'Every new client engagement begins with re-explaining your Frameworks and approach from scratch',
      'Your onboarding requires significant personal time to educate each client on how you work',
      'You find yourself giving the same strategic recommendations to different clients repeatedly',
      'Onboarding takes weeks when it should take days',
      'You are losing billable time to explanation rather than application',
      'Junior team members cannot onboard clients because they do not know your methodology well enough to teach it',
    ],
    forYou: [
      'You have a proprietary methodology that clients need to understand before work begins',
      'You onboard multiple clients per year and want to reduce the time cost',
      'Your methodology is consistent enough to be encoded in the Account Brain',
      'You want Intelligence to apply your Frameworks so you do not have to teach them each time',
    ],
    notForYou: [
      'Every engagement is genuinely unique with no repeatable methodology',
      'You only serve one or two long-term clients with no onboarding challenge',
      'Client education is a core part of your service that you want to keep manual',
    ],
    faqs: [
      { question: 'Is client education really a waste of time?', answer: 'Strategic client education is not. But re-explaining your Framework from scratch with every client is. Client Intelligence shifts from teaching your methodology to applying it. Clients get outcomes faster.' },
      { question: 'What if clients need to understand my Framework to trust the output?', answer: 'You can document your Framework in the Account Brain and share that explanation without manually re-delivering it each time. Intelligence applies the Framework. The documentation explains it.' },
      { question: 'How much onboarding time can I realistically save?', answer: 'Most users reduce onboarding time by 60 to 80%. What previously required 3 to 5 sessions of explanation and setup compresses to one Brain Dump session and Workspace setup.' },
      { question: 'Does this work for complex methodologies that genuinely take time to explain?', answer: 'Especially for those. The more complex your methodology, the more valuable it is to encode it in the Account Brain once rather than re-teach it repeatedly. Intelligence handles the complexity so you do not have to re-explain it.' },
    ],
  },
  {
    slug: 'losing-quality-while-scaling',
    label: 'Losing Quality While Scaling',
    h1: 'Why Quality Drops When You Scale (And How to Fix It)',
    metaDescription: 'Quality dilution during growth is predictable but not inevitable. Client Intelligence encodes your standards in the Account Brain so quality holds as client volume increases.',
    bullets: [
      'Client satisfaction scores have declined as you have added more clients',
      'Deliverables feel less personal and thorough than when you had fewer clients',
      'Reviews and feedback reflect inconsistency that did not exist when you were smaller',
      'You are spending more time fixing quality issues than you used to',
      'You hired to maintain quality but it created new inconsistency problems',
      'Your best clients are getting less attention than when they were your only clients',
    ],
    forYou: [
      'You have experienced quality decline as your client base has grown',
      'You have clear quality standards that could be encoded in the Account Brain',
      'You want to grow further without the quality degradation you have already experienced',
      'You are willing to systematize delivery to preserve what made you good',
    ],
    notForYou: [
      'You have not grown yet and are looking to prevent future quality issues',
      'Your quality is declining for reasons unrelated to scale, such as team issues or market fit',
      'You do not have defined quality standards to systematize',
    ],
    faqs: [
      { question: 'Why does quality decline when you scale?', answer: 'Scale spreads attention thinner across clients, introduces inconsistent team members, and reduces the personal care that made quality high initially. Encoding your standards in the Account Brain prevents all three causes.' },
      { question: 'Can systematizing quality actually improve on what I deliver manually?', answer: 'Yes. Intelligence never has bad days, never cuts corners under deadline pressure, and always applies your full Framework from the Account Brain. Most users find consistency improves beyond manual delivery within 60 days.' },
      { question: 'What about clients who want personal attention specifically?', answer: 'Systematized delivery frees your time for relationship-building. You can spend more time in strategic conversations and less in mechanical delivery. Personal attention increases, not decreases.' },
      { question: 'How do I know if my quality standards are systematizable?', answer: 'If you can describe what good output looks like, it is systematizable. If you can give examples of high-quality deliverables, Intelligence can apply that standard consistently in every client Workspace.' },
    ],
  },
  {
    slug: 'ip-stuck-in-your-head',
    label: 'IP Stuck in Your Head',
    h1: 'Your Best Thinking Is Locked in Your Head. Here\'s How to Change That',
    metaDescription: 'Expertise that lives only in your head is a single point of failure. Client Intelligence helps you extract and encode your intellectual property into the Account Brain using Brain Dump mode.',
    bullets: [
      'Your best Frameworks and insights exist only in your memory and cannot be delegated',
      'New team members cannot reach your expertise level because you cannot fully articulate it',
      'If you are unavailable, client work suffers because your judgment cannot be replicated',
      'You have never successfully documented your methodology because it feels too complex',
      'Your expertise is your business most valuable asset and also its biggest fragility',
      'You have tried to systematize before but it always felt too rigid or too incomplete',
    ],
    forYou: [
      'You have deep expertise that clients pay premium for',
      'You want your methodology to work without requiring your constant presence',
      'You are open to using Brain Dump mode rather than formal documentation',
      'You want to protect your IP from being lost if you are unavailable or if team members leave',
    ],
    notForYou: [
      'Your expertise is truly bespoke and varies completely between every engagement',
      'You prefer your IP to be a competitive moat that lives only with you personally',
      'You have already fully documented your methodology and it is accessible to your team',
    ],
    faqs: [
      { question: 'How do I capture knowledge that feels intuitive and hard to articulate?', answer: 'Brain Dump mode is designed for this. Instead of trying to articulate abstract Frameworks, capture examples. Here is what I would do in this situation, and here is why. Implicit knowledge becomes explicit through concrete examples.' },
      { question: 'What if my IP is constantly evolving?', answer: 'Client Intelligence is designed as a living system. You update your Account Brain as your thinking evolves. The latest version of your Frameworks is always what Intelligence applies.' },
      { question: 'Is there a risk of my IP leaking if it is encoded in a system?', answer: 'No. Your Account Brain is isolated to your account. It is never shared with other users, used for external training, or accessible outside your Workspaces.' },
      { question: 'How long does it realistically take to encode significant expertise?', answer: 'Most users achieve functional coverage, enough for consistent client delivery, in 6 to 10 hours of Brain Dump sessions spread over 2 to 4 weeks. Deep encoding continues over months.' },
    ],
  },
  {
    slug: 'chatgpt-not-working-for-client-work',
    label: 'ChatGPT Not Working for Client Work',
    h1: 'Why ChatGPT Doesn\'t Work for Multi-Client Service Delivery',
    metaDescription: 'ChatGPT is a general intelligence tool. For multi-client professional service delivery, it lacks per-client memory, Framework encoding, and data isolation. That is a structural problem, not a prompting problem.',
    bullets: [
      'ChatGPT starts fresh every session with no memory of your client or your Frameworks',
      'You have to re-explain your methodology every time you want it to apply your approach',
      'There is no way to isolate different clients data when using the same tool',
      'Outputs are generic and do not reflect your proprietary thinking',
      'Quality varies wildly depending on how you prompt it each session',
      'It cannot reference past client work or maintain context across engagements',
    ],
    forYou: [
      'You have tried ChatGPT or similar tools and found them insufficient for serious client work',
      'You need AI that remembers your clients and applies your Frameworks without re-prompting',
      'You serve multiple clients and need guaranteed data isolation via Workspaces',
      'You want AI outputs that reflect your methodology, not generic AI',
    ],
    notForYou: [
      'You only do one-off tasks where session-level memory does not matter',
      'You only serve one client and data isolation is not a concern',
      'You are fine with generic outputs that do not reflect your specific methodology',
    ],
    faqs: [
      { question: 'What specifically does Client Intelligence do that ChatGPT cannot?', answer: 'Three things: (1) Per-client persistent memory across all sessions via isolated Workspaces; (2) Your Frameworks encoded permanently in the Account Brain that applies to every engagement; (3) Structural data isolation between clients. None of these exist in ChatGPT.' },
      { question: 'Cannot I use ChatGPT Custom GPTs or Projects to solve this?', answer: 'Partially. Custom GPTs and Projects help with some memory issues but share infrastructure, do not enforce client data isolation, and require re-building for each use case. Client Intelligence is designed specifically for multi-client professional services.' },
      { question: 'Is the quality difference between ChatGPT and Client Intelligence significant?', answer: 'For client-specific work, yes. When Intelligence has your Frameworks from the Account Brain and the client full context from their Workspace simultaneously, outputs are substantially more relevant and aligned with your methodology than generic ChatGPT prompting.' },
      { question: 'I am used to ChatGPT. Is there a learning curve?', answer: 'Minimal. The interface is similar to what you know. The main addition is setting up Workspaces and running Brain Dump sessions into the Account Brain. A one-time investment that pays ongoing dividends.' },
    ],
  },
  {
    slug: 'generic-ai-fails-for-agencies',
    label: 'Generic AI Failing for Agencies',
    h1: 'Why Generic AI Tools Keep Failing Your Agency',
    metaDescription: 'Generic AI was not built for multi-client service delivery. Agencies need isolated Workspaces, Framework memory in the Account Brain, and consistent application. ChatGPT does not provide any of these.',
    bullets: [
      'Generic AI produces outputs that feel like templates, not your agency approach',
      'Every team member prompts AI differently, creating wildly inconsistent outputs',
      'There is no way to encode your agency methodology so it applies consistently across the team',
      'Client data mixing across your team shared AI tools is a real risk',
      'You spend more time correcting AI outputs than you save using them',
      'Clients can tell when work came from generic AI, and they are not impressed',
    ],
    forYou: [
      'Your agency has a defined methodology or creative approach worth encoding in the Account Brain',
      'You serve multiple clients and need team-wide consistency in AI use',
      'You are tired of correcting generic AI outputs that miss your standards',
      'You want AI that sounds like your agency, not like every other agency',
    ],
    notForYou: [
      'Your agency work is purely bespoke with no repeatable methodology',
      'You have only one or two clients and team consistency is not a concern',
      'Your team does not currently use AI for client deliverables',
    ],
    faqs: [
      { question: 'What makes agency AI use different from individual professional use?', answer: 'Scale, consistency, and team coordination. Agencies need AI that applies the same methodology across all team members for all clients. Generic tools do not provide this. Each person prompts differently and gets different results.' },
      { question: 'How does Client Intelligence handle team-wide methodology consistency?', answer: 'Your agency Frameworks live in the Account Brain, accessible to everyone. Every team member works from the same methodology in every client Workspace regardless of how they prompt. Consistency is structural, not dependent on individual prompting skill.' },
      { question: 'Do different clients need different approaches?', answer: 'Yes, and that is what per-client Workspaces are for. The methodology is consistent from the Account Brain, but application is personalized to each client specific context and data.' },
      { question: 'Is this expensive to roll out across a team?', answer: 'Client Intelligence is designed for service businesses. Account access is shared within your organization so your full team benefits from the same Framework encoding, Workspaces, and Intelligence Mode.' },
    ],
  },
  {
    slug: 'no-leverage-as-consultant',
    label: 'No Leverage as a Consultant',
    h1: 'Why You Have No Leverage as a Consultant (And How AI Changes That)',
    metaDescription: 'Consultants who trade hours for money have no leverage. Client Intelligence turns your expertise into a scalable system by encoding your Frameworks in the Account Brain and applying them across every client Workspace.',
    bullets: [
      'Your revenue is directly capped by your available hours',
      'You have raised your rates but it just means fewer total clients, not more income',
      'You have no meaningful asset in your business beyond your personal availability',
      'You cannot take time off without losing revenue',
      'Your expertise does not scale. Each client gets a finite portion of your time.',
      'You have built expertise worth far more than your hourly rate implies but cannot capture it',
    ],
    forYou: [
      'You want to break the direct link between your hours and your revenue',
      'You have genuine expertise and methodology that could work systematically via the Account Brain',
      'You are willing to invest in building leverage rather than just working harder',
      'You want your business to produce value even when you are not actively working',
    ],
    notForYou: [
      'You are satisfied with a time-for-money model and do not want to change it',
      'You deliberately operate a boutique practice with no scaling intent',
      'You do not have repeatable methodology. Every engagement is completely bespoke.',
    ],
    faqs: [
      { question: 'What does leverage actually mean for a consultant?', answer: 'Leverage means your expertise produces output beyond what your personal time allows. Client Intelligence encodes your methodology in the Account Brain so it applies to multiple clients simultaneously. Your Frameworks work for you rather than requiring you to personally apply them each time.' },
      { question: 'Is AI leverage real or just theoretical?', answer: 'It is measurable. Users who encode their methodology in Client Intelligence and run client Workspaces serve 30 to 80% more clients with the same hours. That is real leverage: more output per unit of personal time.' },
      { question: 'Do courses and products also solve the leverage problem?', answer: 'They solve it by teaching your methodology to others. Client Intelligence solves it by applying your methodology at scale without teaching it. Different model. You remain the expert. Intelligence does the application.' },
      { question: 'What is the first step toward building leverage?', answer: 'Encode your most repeatable Framework into the Account Brain. Even one systematized Framework creates immediate leverage for all the clients where it applies. Start small and expand.' },
    ],
  },
  {
    slug: 'client-work-taking-all-your-time',
    label: 'Client Work Taking All Your Time',
    h1: 'Why Client Work Consumes All Your Time and How to Reclaim It',
    metaDescription: 'If every hour of your workday is consumed by client delivery, you have no time to build, grow, or rest. Client Intelligence encodes your delivery standards and runs repeatable work from client Workspaces so you reclaim your time.',
    bullets: [
      'You spend every working hour on client delivery with nothing left for business development',
      'You cannot work on your own business because client obligations fill every available slot',
      'Marketing, strategy, and growth work get pushed perpetually because clients take priority',
      'You are always behind, always reactive, always serving others priorities',
      'You have not taken a meaningful vacation in years because clients cannot wait',
      'The business is not growing because you have no time to invest in it',
    ],
    forYou: [
      'You want to reclaim time from delivery without reducing client quality',
      'You have methodology worth encoding in the Account Brain rather than pure bespoke delivery',
      'You are ready to invest upfront time to build delivery systems in client Workspaces',
      'You want to be able to take time off without client work suffering',
    ],
    notForYou: [
      'You enjoy full immersion in client work and do not want to change it',
      'Your time is fully allocated by design and you are not looking to change that',
      'You have not identified specific delivery tasks that could be systematized',
    ],
    faqs: [
      { question: 'What types of client delivery tasks are most time-consuming and systematizable?', answer: 'Research, report creation, data analysis, deliverable formatting, follow-up documentation, and strategic recommendation drafts. These high-volume tasks are where Client Intelligence saves the most time through the 16 Skills.' },
      { question: 'How do I reclaim time without my clients noticing?', answer: 'Clients notice output quality, not your process. When Intelligence maintains or improves your output quality using your Account Brain Frameworks, clients experience better service, not less service.' },
      { question: 'How much time can I realistically reclaim?', answer: 'Most users reclaim 4 to 10 hours per week within 60 days. At $200 to $500 or more per hour billing rates, this represents $800 to $5,000 of reclaimed capacity per week, either for more clients or for personal time.' },
      { question: 'Will setting up systems take even more time initially?', answer: 'Yes. The setup investment is typically 4 to 8 hours spread over a few weeks. The ongoing savings return that investment within the first month for most users.' },
    ],
  },
  {
    slug: 'inconsistent-delivery-across-clients',
    label: 'Inconsistent Delivery Across Clients',
    h1: 'Why Delivery Quality Varies Across Clients and How to Fix It',
    metaDescription: 'Some clients get your best work. Others get rushed deliverables. Client Intelligence encodes your standards in the Account Brain so every client receives consistent, high-quality delivery from their isolated Workspace.',
    bullets: [
      'Some clients receive significantly better deliverables than others depending on your workload',
      'Quality varies based on which team member handles the account',
      'Client feedback is inconsistent. Some love your work. Some are underwhelmed.',
      'Your best work only happens when you are personally involved',
      'Smaller or less demanding clients receive less thorough work by default',
      'You cannot honestly say that every client receives your full methodology',
    ],
    forYou: [
      'You have quality standards you want applied consistently to every client',
      'You serve multiple clients at different priority levels and want to standardize quality',
      'You have a team whose individual quality varies significantly',
      'You want Intelligence to enforce your standards regardless of workload pressure',
    ],
    notForYou: [
      'You intentionally differentiate service quality by contract tier',
      'You only serve one client and consistency is not a challenge',
      'Your delivery is inherently bespoke with no standard quality criteria',
    ],
    faqs: [
      { question: 'Why does delivery quality naturally vary across clients?', answer: 'Human delivery under variable conditions, time pressure, fatigue, competing priorities, produces variable output. Intelligence is consistent by nature: it always applies your full Framework from the Account Brain regardless of workload pressure.' },
      { question: 'What if different clients need genuinely different delivery styles?', answer: 'Per-client Workspaces handle this. The core methodology is consistent from the Account Brain, but each Workspace applies it to that client specific context and expectations.' },
      { question: 'How do I know which specific things to standardize?', answer: 'Start with your most common deliverable types and your most repeatable Framework applications. What do you produce for most clients? Encode that in the Account Brain first.' },
      { question: 'Will AI consistency feel robotic to clients?', answer: 'Consistency does not mean sameness. Because Intelligence applies your Framework to each client unique context via their Workspace, outputs are personalized and feel considered, just reliably so rather than variable.' },
    ],
  },
  {
    slug: 'ai-confidentiality-concerns',
    label: 'AI Confidentiality Concerns',
    h1: 'Why AI Confidentiality Is a Real Problem for Client-Serving Businesses',
    metaDescription: 'Using general AI tools with client data creates genuine confidentiality risks. Client Intelligence provides architectural data isolation at the Workspace level designed for professional services.',
    bullets: [
      'Your current AI tools share infrastructure that does not guarantee client data isolation',
      'You avoid using AI for your most sensitive client work because of data risk',
      'Clients ask about your data handling and you do not have a satisfying answer',
      'Your service agreements include data handling clauses your current AI tools may violate',
      'You have had near-misses where AI surfaced details that seemed to belong to other contexts',
      'Legal and compliance reviews of your AI tool stack have flagged concerns',
    ],
    forYou: [
      'You serve clients with confidential business information',
      'Your contracts include data isolation or confidentiality obligations',
      'You want to use AI freely for client work without confidentiality constraints',
      'You want to be able to honestly communicate your data handling to clients',
    ],
    notForYou: [
      'You only serve one client and cross-contamination is impossible',
      'Your client work involves no confidential information',
      'Confidentiality requirements have been waived for your specific use case',
    ],
    faqs: [
      { question: 'What specific confidentiality risks exist with generic AI tools?', answer: 'Data pooling in shared infrastructure, conversation history accessible across sessions, potential use in model training, and inability to demonstrate client-specific isolation. These are architectural limitations of general AI tools, not prompting problems.' },
      { question: 'How is Client Intelligence confidentiality approach different?', answer: 'Data isolation is architectural. Each client Workspace is structurally separated at the data layer, not just via access controls or system prompts. One client data cannot appear in another Workspace.' },
      { question: 'Can I share Client Intelligence data handling terms with clients?', answer: 'Yes. Privacy and data handling documentation is available to share with clients who require vendor review. Many professional services users find clients appreciate the proactive transparency.' },
      { question: 'Does this solve GDPR and other regulatory requirements?', answer: 'Workspace isolation addresses the core data separation requirements of most regulations. For specific compliance questions, review the detailed privacy documentation or contact Client Intelligence directly. Requirements vary by jurisdiction and use case.' },
    ],
  },
  {
    slug: 'scaling-without-systems',
    label: 'Scaling Without Systems',
    h1: 'You\'re Trying to Scale Without Systems. Here\'s What That Costs You',
    metaDescription: 'Scaling by working harder is not scaling. Without systems, growth creates chaos. Client Intelligence provides the delivery systems that make real scale possible through the Account Brain and client Workspaces.',
    bullets: [
      'You have added clients but your operations have not changed. You are just working more.',
      'Growth feels chaotic rather than organized and replicable',
      'New clients take as much effort to serve as the first ones did',
      'You are working more hours than when you had half the clients',
      'Quality and consistency issues have increased as volume has grown',
      'You know you need systems but have not had time to build them',
    ],
    forYou: [
      'You are actively growing and need delivery systems to match your ambition',
      'You have repeatable delivery work worth systematizing in the Account Brain',
      'You are ready to invest in infrastructure rather than just adding hours',
      'You want growth to create leverage, not just more work',
    ],
    notForYou: [
      'You are not growing and are not planning to',
      'Your delivery is truly one-of-a-kind with no repeatable elements',
      'You prefer to stay small and boutique intentionally',
    ],
    faqs: [
      { question: 'What is the difference between working harder and systematizing?', answer: 'Working harder hits a ceiling defined by your available time. Systematizing creates leverage where your output grows faster than your input. Client Intelligence is the systematization layer that makes this possible for service businesses through the Account Brain and Workspaces.' },
      { question: 'I know I need systems. Why have I not built them?', answer: 'Building systems requires time you do not have while you are running at capacity. Client Intelligence reduces the build cost by making Framework encoding fast via Brain Dump mode and Workspace setup immediate.' },
      { question: 'How do I start building systems while still serving existing clients?', answer: 'Start with your next onboarding. Create one Workspace, encode one Framework in the Account Brain, and run one client through the system. Build incrementally rather than trying to systematize everything at once.' },
      { question: 'What is the ROI of investing in delivery systems?', answer: 'Typically 3 to 6 months to recoup the setup investment, then ongoing leverage. Users who systematize can serve 30 to 80% more clients without proportional hour increases, representing real economic upside.' },
    ],
  },
  {
    slug: 'methodology-not-being-applied',
    label: 'Your Methodology Not Being Applied Consistently',
    h1: 'Why Your Methodology Is Not Being Applied Consistently to Every Client',
    metaDescription: 'You have a methodology. Your team does not apply it consistently. Client Intelligence encodes your Frameworks in the Account Brain so they are applied the same way every time, by everyone, in every client Workspace.',
    bullets: [
      'Different team members interpret and apply your methodology differently',
      'Clients get different experiences depending on who handles their account',
      'Your methodology is documented but not consistently followed in practice',
      'You find yourself correcting team members who have drifted from the Framework',
      'Your most experienced people apply your methodology. Everyone else improvises.',
      'Methodology enforcement requires your direct supervision to maintain',
    ],
    forYou: [
      'You have a defined methodology and expect it to be applied consistently',
      'You have a team whose individual application varies',
      'You want Intelligence to enforce your standards without requiring your constant oversight',
      'Your methodology is stable enough to be encoded in the Account Brain',
    ],
    notForYou: [
      'You are a solo practitioner with no team consistency problem',
      'Your methodology is too new or too fluid to encode yet',
      'Consistent application is not a goal. You prefer individual flexibility.',
    ],
    faqs: [
      { question: 'Why do team members not apply my methodology consistently?', answer: 'Even with documentation, humans interpret, adapt, and drift from Frameworks under pressure. Encoding your methodology in the Account Brain makes it the structural starting point in every client Workspace, not a document people may or may not consult.' },
      { question: 'Will encoding my methodology constrain my team creativity?', answer: 'Your methodology is the foundation, not a cage. Team members still bring creativity to strategy and relationship work. Intelligence applies the Framework. Humans bring judgment and nuance within it.' },
      { question: 'How do I know if my methodology is defined well enough to encode?', answer: 'If you can describe what correct application looks like, it is encodable. If you can identify when someone has applied it incorrectly, those criteria are exactly what goes into the Account Brain.' },
      { question: 'What happens when my methodology evolves?', answer: 'Update your Account Brain and the improvement applies everywhere immediately. One update changes what every team member produces for every client. A force multiplier for methodology improvement.' },
    ],
  },
  {
    slug: 'cant-clone-yourself',
    label: 'Can\'t Clone Yourself',
    h1: 'You Can\'t Clone Yourself. But Your AI Can.',
    metaDescription: 'The biggest constraint in any expert-led service business is that the expert cannot be everywhere. Client Intelligence encodes your expertise in the Account Brain so Intelligence operates like you across every client Workspace.',
    bullets: [
      'Clients want you specifically, but there is only one of you',
      'Your junior team cannot deliver at your level because they do not think like you',
      'You are the constraint. Everything good in your business runs through you.',
      'You have thought about cloning yourself but actually meant systematizing your thinking',
      'Your expertise is your most valuable asset and also your most limited one',
      'You cannot serve every client who wants you personally',
    ],
    forYou: [
      'You have clearly identifiable expertise and methodology that can be encoded in the Account Brain',
      'You want your team to deliver at your level without requiring your personal involvement',
      'You are the limiting factor in your own business and want to change that',
      'You understand that encoding your thinking in the Account Brain is a form of intellectual leverage',
    ],
    notForYou: [
      'Your expertise is irreducibly human and cannot be systematized at any level',
      'You prefer to serve fewer clients at premium prices rather than scale delivery',
      'You are deliberately running a boutique practice where clients get you personally',
    ],
    faqs: [
      { question: 'Can AI really replicate how I think?', answer: 'Not perfectly, and it does not need to. It replicates your methodology and Frameworks from the Account Brain, applying them consistently to every client situation in their Workspace. The output is your thinking systematically applied, not you personally.' },
      { question: 'What parts of my expertise cannot be replicated by Intelligence?', answer: 'Genuine relationship insight, novel creative judgment, and the human empathy that builds trust. Intelligence handles the Framework application. You handle the uniquely human elements.' },
      { question: 'Will clients accept work that does not come from me personally?', answer: 'Clients accept excellent, consistent, on-Framework work. Whether they know Intelligence is involved depends on your disclosure choice. Most notice quality improvement, not quality substitution.' },
      { question: 'Is this about replacing myself or multiplying myself?', answer: 'Multiplying. Client Intelligence does not remove you from the picture. It multiplies the reach of your expertise. You remain the source. Intelligence becomes the delivery mechanism at scale.' },
    ],
  },
  {
    slug: 'spending-too-long-per-client',
    label: 'Spending Too Long Per Client',
    h1: 'Why You\'re Spending Too Long Per Client (And How to Fix It)',
    metaDescription: 'If each client engagement takes longer than it should, you are leaving capacity and revenue on the table. Client Intelligence systematizes the time-consuming parts of delivery through the Account Brain and client Workspaces.',
    bullets: [
      'Your per-client time far exceeds your original estimates when pricing engagements',
      'You are effectively working at a fraction of your intended hourly rate after actual hours',
      'Deliverable creation, research, and documentation consume the majority of your client time',
      'Each new client takes as long as the ones before with no efficiency gains over time',
      'You cannot take on more clients without losing money on the new ones',
      'Time overruns are your main barrier to profitability',
    ],
    forYou: [
      'You track your time and know per-client hours exceed your targets',
      'Your engagement delivery includes significant research, drafting, and documentation',
      'You want to reduce per-client time without reducing quality or scope',
      'You have enough clients that per-client efficiency compounds meaningfully',
    ],
    notForYou: [
      'Your engagements are billed hourly and longer time means more revenue',
      'Your per-client time is already at target',
      'Time per client is not your primary business constraint',
    ],
    faqs: [
      { question: 'Where do most consultants lose time per client?', answer: 'Predominantly in research, deliverable creation, meeting prep, and documentation. The systematic tasks. Strategy and relationship work is typically efficient. Client Intelligence handles the systematic time-sinks using the 16 Skills.' },
      { question: 'How much can per-client time realistically be reduced?', answer: 'Most users see 30 to 50% reduction in per-client delivery time within 60 days. The biggest gains are in research, report generation, and documentation, often 60 to 80% faster with Intelligence.' },
      { question: 'Will reducing time per client reduce the quality clients expect?', answer: 'Only if quality comes from hours rather than methodology. When Intelligence applies your methodology from the Account Brain thoroughly and consistently in each Workspace, quality improves while time decreases.' },
      { question: 'Should I use time savings to serve more clients or to reduce my working hours?', answer: 'Both options are valid. Some users add clients and grow revenue. Others maintain their client count and reclaim personal time. Client Intelligence makes the choice yours.' },
    ],
  },
  {
    slug: 'team-not-applying-frameworks',
    label: 'Team Not Applying Frameworks Correctly',
    h1: 'Why Your Team Isn\'t Applying Your Frameworks Correctly',
    metaDescription: 'Documenting Frameworks does not mean they get used. Client Intelligence makes your Frameworks the structural foundation of every team member work in every client Workspace, not a document they might consult.',
    bullets: [
      'You have documented your Frameworks but team members still produce inconsistent outputs',
      'New hires take 6 to 12 months before they apply your methodology reliably',
      'Your senior people apply your Frameworks. Junior people improvise around them.',
      'Client feedback reflects Framework inconsistency that documentation has not fixed',
      'You spend significant time reviewing and correcting Framework misapplication',
      'Training sessions help temporarily but drift resumes within weeks',
    ],
    forYou: [
      'You have a defined Framework and invest in team training',
      'You experience ongoing inconsistency despite documentation and training efforts',
      'You want Framework application to be structural, not dependent on individual discipline',
      'You are willing to encode your Frameworks in the Account Brain so they enforce themselves',
    ],
    notForYou: [
      'You are solo with no team to coordinate',
      'Your teams apply your Frameworks well and consistency is not a problem',
      'You prefer Framework flexibility over consistency',
    ],
    faqs: [
      { question: 'Why do documentation and training not solve Framework inconsistency?', answer: 'Documentation is passive and training fades. When Frameworks are encoded in the Account Brain, they are the active starting point for every deliverable in every client Workspace, not something team members have to remember to consult.' },
      { question: 'How does this affect onboarding new team members?', answer: 'Dramatically. New hires can produce on-Framework outputs from their first week because the Framework is built into every client Workspace via the Account Brain. The 6 to 12 month ramp time compresses to days.' },
      { question: 'Will team members resist using Intelligence for their work?', answer: 'Most embrace it. Client Intelligence handles the systematic application work that professionals find least rewarding. Research, formatting, documentation. Their time goes to the judgment work they value.' },
      { question: 'What if my team adapts the Framework to their own style?', answer: 'That is still possible at the refinement stage, reviewing and adding nuance to Intelligence-generated outputs. The structural Framework application from the Account Brain is consistent. Individual judgment and voice are still expressed.' },
    ],
  },
  {
    slug: 'new-clients-take-too-long-to-onboard',
    label: 'New Clients Take Too Long to Onboard',
    h1: 'Why Client Onboarding Takes So Long (And How AI Fixes It)',
    metaDescription: 'Long onboarding delays your revenue and frustrates new clients. Client Intelligence compresses onboarding from weeks to days by pre-loading your Frameworks in the Account Brain and using Brain Dump mode for rapid context capture.',
    bullets: [
      'New clients wait 2 to 4 weeks before substantive work can begin',
      'Onboarding requires multiple context-gathering sessions that feel repetitive to clients',
      'You have to re-explain your methodology to each new client before applying it',
      'The client background information must be manually reviewed before every engagement',
      'Delayed starts cost you revenue and erode client enthusiasm during the wait',
      'Your onboarding process has not improved meaningfully as you have grown',
    ],
    forYou: [
      'You take on new clients regularly enough that onboarding efficiency matters',
      'Your onboarding involves significant context capture and methodology explanation',
      'You want new clients delivering value to themselves faster after they sign',
      'Your current onboarding time is a competitive disadvantage',
    ],
    notForYou: [
      'You rarely onboard new clients and current duration is acceptable',
      'Your engagements are long-term retainers where onboarding time is immaterial',
      'Your onboarding is already fast and not a pain point',
    ],
    faqs: [
      { question: 'What makes client onboarding so time-consuming?', answer: 'Context capture (understanding the client), methodology explanation (helping them understand your process), and Workspace setup (getting everything organized to work effectively). Client Intelligence compresses all three.' },
      { question: 'How does Client Intelligence compress onboarding time?', answer: 'Your methodology is pre-loaded in the Account Brain so no explanation is needed. Brain Dump mode captures client context in one session rather than multiple. The Workspace is ready with full context before the first working session begins.' },
      { question: 'What is the realistic onboarding time reduction?', answer: 'Most users reduce onboarding from 2 to 4 weeks to 3 to 5 days. The biggest gains come from pre-loaded Frameworks in the Account Brain and single-session context capture via Brain Dump mode.' },
      { question: 'Will faster onboarding compromise client relationship building?', answer: 'The opposite. Faster onboarding means clients see value sooner. Relationship quality comes from delivery quality and communication, not from lengthy intake processes.' },
    ],
  },
  {
    slug: 'losing-context-between-client-meetings',
    label: 'Losing Context Between Client Meetings',
    h1: 'Why You Keep Losing Context Between Client Meetings',
    metaDescription: 'Forgetting what happened last session is embarrassing and costly. Client Intelligence maintains complete, searchable context for every client across every interaction through auto-captured Facts and Workspace session history.',
    bullets: [
      'You spend the first 10 minutes of every client meeting re-establishing context from last time',
      'You sometimes refer to decisions or details that have changed since your last meeting',
      'Clients notice when you have forgotten something they told you and trust erodes',
      'Your notes from previous sessions are disorganized and hard to review quickly',
      'When sessions are spaced weeks apart, context loss is significant and visible',
      'Your clients expect you to remember everything and you cannot without better systems',
    ],
    forYou: [
      'You have ongoing client relationships spanning multiple sessions',
      'You serve enough clients that manual context review before each session is impractical',
      'You value appearing fully prepared in every client interaction',
      'You want to build a complete, searchable record of each client relationship',
    ],
    notForYou: [
      'You only have one or two long-term clients where manual review is practical',
      'Your engagements are one-time projects with no ongoing relationship',
      'You already have strong note and context management systems that work for you',
    ],
    faqs: [
      { question: 'How does Client Intelligence prevent context loss between sessions?', answer: 'Every session transcript, note, and decision you add to a client Workspace is permanently stored. Facts are auto-extracted from conversations. Before each meeting, open the Workspace and ask Intelligence to surface what is most relevant. Full preparation in minutes.' },
      { question: 'What is the best way to add context after each session?', answer: 'Upload the meeting transcript if recorded. Key decisions made, open questions, and next steps. A 5-minute post-session upload means full context is available the moment you need it next time.' },
      { question: 'Can I access client context on mobile before meetings?', answer: 'Client Intelligence is web-accessible. You can review Workspace context on any device before a session, including while commuting to an in-person meeting.' },
      { question: 'What if clients notice I am referencing notes rather than remembering everything?', answer: 'Clients universally prefer a consultant who references accurate records over one who relies on memory alone. Transparent preparation signals professionalism, not weakness.' },
    ],
  },
]
