export interface UseCasePage {
  slug: string
  label: string
  h1: string
  metaDescription: string
  steps: { step: string; title: string; body: string }[]
  scenarios: { title: string; story: string; result: string }[]
  faqs: { question: string; answer: string }[]
}

export const useCases: UseCasePage[] = [
  {
    slug: 'scale-consulting-without-hiring',
    label: 'Scale Consulting Without Hiring',
    h1: 'How to Scale Your Consulting Business Without Hiring Anyone',
    metaDescription: 'Solo consultants use Client Intelligence to take on more clients and deliver better results without adding headcount. Here is how it works.',
    steps: [
      { step: '1', title: 'Load Your Methodology into the Brain', body: 'Use Brain Dump mode to capture your frameworks, SOPs, and examples. Voice memos, PDFs, transcripts. Your methodology goes into the Account Brain once and stays there.' },
      { step: '2', title: 'Create an Isolated Workspace per Client', body: 'Each client gets their own Workspace. Their data, history, and documents live there and nowhere else. Your AI always knows exactly which client it is working on.' },
      { step: '3', title: 'Run Intelligence Mode to Apply Your Frameworks', body: 'Open a client Workspace and run Intelligence Mode. Your Brain is already in context. Generate tailored deliverables from your methodology without starting from scratch.' },
      { step: '4', title: 'Use the 16 Skills for Repeatable Outputs', body: 'Client Intelligence includes 16 action and output Skills. Assign the right Skills to repeatable delivery tasks. You review final outputs rather than build everything from zero.' },
    ],
    scenarios: [
      { title: 'The Capacity-Capped Consultant', story: 'Marcus ran a six-figure consulting practice and could not take a fifth client. Every client required full context switching and manual work. He was stuck at four.', result: 'After loading his Frameworks into the Account Brain and creating isolated Workspaces per client, Marcus serves seven clients in the same hours. His NPS went up, not down.' },
      { title: 'The Quality-Conscious Solopreneur', story: 'Priya was afraid that scaling would mean diluting the quality her clients paid for. She had watched other consultants grow fast and lose what made them good.', result: 'With her Frameworks encoded in Client Intelligence, every client receives the same methodology. Quality improved because Intelligence never forgets to apply the right Framework.' },
      { title: 'The Referral Growth Trap', story: 'Dan kept getting referrals and kept turning them away. He had no capacity. He was losing real money every month saying no to pre-sold prospects.', result: 'Dan routes new clients into dedicated Workspaces immediately. Onboarding dropped from three sessions to one Brain Dump. He has not turned away a referral in six months.' },
    ],
    faqs: [
      { question: 'Can I really scale without hiring?', answer: 'Yes. Most consultants who cannot scale are limited by the time it takes to apply their thinking to each new client. Client Intelligence removes that bottleneck by encoding your Frameworks once and applying them to every client automatically.' },
      { question: 'Does this work if my consulting is highly customized?', answer: 'Especially if it is highly customized. Your Frameworks stay in your Account Brain while each client context lives in their isolated Workspace. You get customization plus consistency at the same time.' },
      { question: 'What happens to quality when I take on more clients?', answer: 'Quality improves. Intelligence never forgets to apply your methodology, never skips a step, and always has full context from the client history. Most users report better delivery consistency after onboarding.' },
      { question: 'How long does it take to set up?', answer: 'Most users are operational within one working session. You Brain Dump your existing Frameworks, create your first Workspaces, and the system is ready the same day.' },
    ],
  },
  {
    slug: 'train-ai-on-your-framework',
    label: 'Train AI on Your Framework',
    h1: 'How to Train AI on Your Proprietary Consulting Framework',
    metaDescription: 'Stop using generic AI. Learn how to encode your exact methodology into the Account Brain so every client interaction starts from your thinking, not a generic model.',
    steps: [
      { step: '1', title: 'Brain Dump Your Frameworks', body: 'Use Brain Dump mode to upload your Frameworks, models, SOPs, and examples. Voice memos, PDFs, slide decks. Any format that contains your thinking works.' },
      { step: '2', title: 'Organize Your IP in the Account Brain', body: 'Client Intelligence structures your raw input into organized, AI-readable Frameworks. Your methodology becomes the permanent foundation Intelligence reasons from in every session.' },
      { step: '3', title: 'Test Against Real Client Scenarios', body: 'Open a client Workspace and test how Intelligence applies your Frameworks to actual client questions. Refine until the outputs sound like you wrote them.' },
      { step: '4', title: 'Deploy Across Every Client Engagement', body: 'Your encoded Frameworks are now available in every client Workspace. Every deliverable and recommendation starts from your methodology, not generic templates.' },
    ],
    scenarios: [
      { title: 'The Proprietary Methodology Owner', story: 'Sarah had spent ten years developing a unique revenue acceleration framework. When she tried generic AI for client work, the outputs did not reflect her model at all.', result: 'After encoding her Framework in the Account Brain, AI outputs are so aligned with her thinking that clients ask if she wrote them personally. Her Framework is now the default for every client.' },
      { title: 'The IP-Protective Consultant', story: 'James was reluctant to use AI because he did not want his proprietary Frameworks entering a shared AI system where competitors might benefit.', result: 'Client Intelligence keeps his Framework in his isolated account. It is never used to train other users. James uses AI freely knowing his IP stays protected.' },
      { title: 'The Framework Inconsistency Problem', story: 'Chen led a two-person consulting firm. When his associate applied their Framework, the outputs were inconsistent. Clients could tell which consultant was doing the work.', result: 'By encoding their shared Framework into the Account Brain, both consultants now produce consistent outputs. Clients cannot tell who did the work. That is the point.' },
    ],
    faqs: [
      { question: 'Does training AI on my Framework require technical skills?', answer: 'None. You upload your Frameworks in whatever form they exist. Documents, slides, transcripts, voice notes. Client Intelligence organizes them into AI-readable IP. No coding required.' },
      { question: 'Will my Framework be used to train other users?', answer: 'Never. Your Account Brain is completely isolated to your account. Your IP stays yours. It is never used for training, shared with other users, or accessible outside your Workspaces.' },
      { question: 'What formats can I upload?', answer: 'PDFs, Word documents, slide decks, plain text, transcripts, and voice recordings that are transcribed automatically. If it contains your thinking, Client Intelligence can work with it.' },
      { question: 'How does this differ from just adding a system prompt to ChatGPT?', answer: 'A system prompt is a one-time instruction in a single conversation. The Account Brain permanently encodes your Framework into persistent memory that applies across all Workspaces and all sessions, with full client context alongside it.' },
    ],
  },
  {
    slug: 'productize-your-methodology',
    label: 'Productize Your Methodology',
    h1: 'How to Productize Your Consulting Methodology with AI',
    metaDescription: 'Turn your consulting expertise into a repeatable AI-driven delivery system. Productize your methodology without building a course or selling templates.',
    steps: [
      { step: '1', title: 'Document Your Repeatable Process', body: 'Identify the three to seven core steps every client goes through and the Frameworks you apply at each stage. These become the skeleton of your productized methodology.' },
      { step: '2', title: 'Encode in the Account Brain', body: 'Upload your full methodology into the Account Brain using Brain Dump mode. Include your decision criteria, diagnostic questions, and example outputs for each stage.' },
      { step: '3', title: 'Build Client-Specific Application in Workspaces', body: 'Each client Workspace inherits your methodology but applies it to that client unique context. Productized process, personalized delivery.' },
      { step: '4', title: 'Run Delivery Using the 16 Skills', body: 'Use Client Intelligence Skills to handle repeatable deliverables within each methodology stage. You spend time on insight and judgment, not formatting and documentation.' },
    ],
    scenarios: [
      { title: 'The Trapped Expert', story: 'Nina methodology was brilliant but lived entirely in her head. Every new client required her to re-explain, re-teach, and re-apply everything from scratch. She could not take vacation.', result: 'After productizing her methodology in the Account Brain, Nina onboards new clients using a documented, AI-driven process. She took a two-week trip and did not lose a single client.' },
      { title: 'The Inconsistent Delivery Problem', story: 'Anthony team of three consultants all applied his methodology differently. Clients had wildly different experiences depending on who led their account.', result: 'With the methodology encoded in the Account Brain and all three consultants using shared Workspaces, consistency went from 60% to 95%. Client feedback became uniformly positive.' },
      { title: 'The Undercharging Expert', story: 'Fatima was charging $5k per engagement because each one took three months of her time. Her methodology had real value but delivery was capped by hours.', result: 'After productizing her methodology with AI-driven delivery, Fatima delivers the same outcomes in six weeks. She doubled her client capacity without reducing her fees.' },
    ],
    faqs: [
      { question: 'Is this just another template system?', answer: 'No. Templates produce generic outputs. Client Intelligence applies your methodology to each client specific context, their data, history, and goals, and generates outputs that reflect their situation, not a generic example.' },
      { question: 'Can I productize a methodology that is not fully documented yet?', answer: 'Yes. Brain Dump mode is designed for this. You can speak, upload, or paste fragmented knowledge and the Account Brain structures it into a coherent, deployable methodology.' },
      { question: 'Will this replace my judgment as a consultant?', answer: 'No. Client Intelligence handles the repeatable application of your Framework. Research, documentation, formatting, analysis. Your judgment on strategy and nuanced decisions stays essential.' },
      { question: 'What is the difference between productizing for AI versus building a course?', answer: 'A course teaches others your methodology. Productizing for AI lets you apply it at scale yourself, faster, more consistently, across more clients, without giving away your expertise.' },
    ],
  },
  {
    slug: 'apply-frameworks-to-every-client',
    label: 'Apply Frameworks to Every Client',
    h1: 'How to Apply Your Methodology to Every Client Without Thinking About It',
    metaDescription: 'Stop forgetting to apply your own Frameworks. Client Intelligence ensures your methodology runs in context every time you open a client Workspace.',
    steps: [
      { step: '1', title: 'Load Your Frameworks into the Account Brain Once', body: 'Upload all your Frameworks, models, and decision criteria to the Account Brain. This happens once, not per client.' },
      { step: '2', title: 'Open a Client Workspace', body: 'Every client Workspace automatically pulls from your Account Brain. Your methodology is in context before you type a single word.' },
      { step: '3', title: 'Generate Framework-Aligned Deliverables', body: 'Ask Intelligence to create recommendations, analyses, or reports. It reasons from your Frameworks first, then applies them to the client specific data and Facts.' },
      { step: '4', title: 'Review and Refine', body: 'You review the output through your expert lens. Refine where needed. Add corrections back to the Account Brain so application gets more accurate over time.' },
    ],
    scenarios: [
      { title: 'The Methodology Drift Problem', story: 'Tom built a rigorous six-step consulting process. Under pressure, he kept skipping steps for larger or more demanding clients. Quality drifted without him noticing.', result: 'With his Frameworks encoded in the Account Brain, every engagement starts from the full methodology. Intelligence applies all six steps and flags when something is missing.' },
      { title: 'The Framework Forgetting Trap', story: 'Leila had Frameworks for twelve different consulting scenarios. In the moment with a client, she defaulted to her two most familiar and forgot the others existed.', result: 'Her Account Brain now surfaces the right Framework for each client situation. She applies all twelve routinely. Clients consistently call her the most thorough consultant they have worked with.' },
      { title: 'The New Associate Onboarding Problem', story: 'David brought on a junior consultant to help with delivery. Teaching them to apply his methodology correctly took months, and outputs were still inconsistent for a year.', result: 'After encoding his methodology in the Account Brain, the new associate produces on-Framework outputs immediately. Onboarding went from months to one week.' },
    ],
    faqs: [
      { question: 'What if my Framework is complex and multi-layered?', answer: 'That is exactly what Client Intelligence is built for. Upload the full complexity including decision trees, conditionals, and exceptions. Intelligence handles that nuance when applying it to each client situation.' },
      { question: 'Does this work for custom Frameworks or only established methodologies?', answer: 'Your proprietary Frameworks work best here. Client Intelligence is designed to encode your unique thinking, not replicate generic consulting models that already exist.' },
      { question: 'Can I have multiple Frameworks for different client types?', answer: 'Yes. Your Account Brain holds multiple Frameworks. When you open a client Workspace, you direct Intelligence to apply the relevant Framework for that engagement type.' },
      { question: 'How do I know Intelligence is applying my Framework correctly?', answer: 'You review its outputs through your expert judgment. Most users run a few test scenarios during setup to calibrate, then find accuracy is high enough that corrections become rare.' },
    ],
  },
  {
    slug: 'keep-client-data-separate',
    label: 'Keep Client Data Separate in AI',
    h1: 'How to Keep Every Client Data Completely Separate in AI',
    metaDescription: 'Running multiple client engagements in ChatGPT risks data mixing. Client Intelligence gives every client a structurally isolated Workspace where data never crosses.',
    steps: [
      { step: '1', title: 'Create a Workspace Per Client', body: 'Every client gets their own isolated Workspace. Documents, transcripts, notes, and history for Client A never appear in Client B Workspace. The isolation is architectural, not a setting.' },
      { step: '2', title: 'Upload Client-Specific Data to Their Workspace', body: 'Add calls, contracts, strategy docs, and correspondence to each client Workspace. All stored in isolation. Data is never pooled across clients.' },
      { step: '3', title: 'Run Intelligence Entirely Within Workspace Context', body: 'Intelligence in each Workspace only has access to that client data. Facts auto-extracted from conversations stay in that Workspace. Cross-client contamination is structurally impossible.' },
      { step: '4', title: 'Maintain Clean Records Over the Engagement Lifetime', body: 'All interactions within a client Workspace are logged there. Audit trails are clean and client-specific for the full lifetime of the engagement.' },
    ],
    scenarios: [
      { title: 'The Confidentiality Crisis Near-Miss', story: 'Amanda was using a single ChatGPT project for three clients. In one session, the AI referenced a strategy detail from a competitor engagement. She caught it, barely.', result: 'After moving to Client Intelligence with isolated Workspaces, Amanda has structural guarantee that cross-client data mixing cannot happen. She has peace of mind. So do her clients.' },
      { title: 'The NDA Compliance Pressure', story: 'Greg served clients in the same industry who were direct competitors. His NDAs required strict information barriers. Using shared AI tools was a contract risk.', result: 'Client Intelligence isolated Workspaces satisfy his NDA requirements. Each competitor engagement is fully walled off. Greg renewed three at-risk contracts after switching.' },
      { title: 'The Client Discovery Incident', story: 'A client asked Rachel what AI tools she used. When she described her workflow, they asked: "How do you keep our data from mixing with other clients?" She had no good answer.', result: 'Rachel now leads with Workspace isolation in her pitch. It became a selling point. Three clients told her it was the deciding factor in choosing her over alternatives.' },
    ],
    faqs: [
      { question: 'Is Workspace isolation guaranteed or just a best-effort setting?', answer: 'It is architectural. Client Workspaces are isolated at the data layer, not just via permissions or prompts. One client data cannot appear in another client Workspace by design.' },
      { question: 'What about my shared Frameworks and methodology?', answer: 'Your Frameworks live in your Account Brain, which is your data, not your clients. Client data is isolated per Workspace. Your Frameworks are shared infrastructure that you control and own.' },
      { question: 'Can I tell clients their data is isolated without overstating it?', answer: 'Yes. The isolation is real and architecturally enforced. Most users share this with clients directly and find it increases trust and reduces compliance friction.' },
      { question: 'What happens if I accidentally upload data to the wrong Workspace?', answer: 'You can delete and re-upload. Data does not propagate between Workspaces. A mis-uploaded file only exists in the Workspace you put it in and can be removed without risk.' },
    ],
  },
  {
    slug: 'build-client-specific-ai',
    label: 'Build Client-Specific AI',
    h1: 'How to Build an AI System That Knows Each Client Individually',
    metaDescription: 'Generic AI does not know your clients. Client Intelligence builds persistent, growing AI memory for every client you serve so context never resets between sessions.',
    steps: [
      { step: '1', title: 'Initialize Each Client Workspace', body: 'Create a Workspace for each client. Upload their onboarding information, goals, challenges, and any documentation from prior engagements. This seeds the AI memory.' },
      { step: '2', title: 'Let Facts Auto-Extract from Every Conversation', body: 'Client Intelligence automatically extracts Facts from conversations and logs them to the client Workspace. Key details are captured without manual note-taking.' },
      { step: '3', title: 'Let Intelligence Reference Full Client History', body: 'When working in a client Workspace, Intelligence has access to everything ever uploaded about that client. No re-explaining. No context loss between sessions.' },
      { step: '4', title: 'Generate Deeply Personalized Deliverables', body: 'Because Intelligence knows the client full history through their Facts and uploaded documents, outputs reference their specific situation, not generic best practices. Clients notice the difference.' },
    ],
    scenarios: [
      { title: 'The Context Reset Frustration', story: 'Danielle started every AI session for each client by re-explaining the situation. With twenty clients, she spent an hour per week just priming AI with context she had already given.', result: 'With Client Intelligence, context is permanent. She opens a Workspace and Intelligence already knows the client full history. That hour per week is now billable.' },
      { title: 'The Long-Term Client Relationship', story: 'Victor had a client he worked with for three years. The depth of context he had built was enormous but lived only in his memory and scattered notes.', result: 'After uploading three years of engagement history into a single client Workspace, Victor surfaces any past decision or recommendation instantly. Intelligence knows the relationship as well as he does.' },
      { title: 'The Handoff Problem', story: 'When Mei went on maternity leave, her colleague had to take over a major client. The handoff took two weeks of meetings just to transfer context.', result: 'With the client full history in their Client Intelligence Workspace, Mei colleague was fully operational in one afternoon. The client did not notice a disruption.' },
    ],
    faqs: [
      { question: 'How much history can each client Workspace hold?', answer: 'There is no practical cap for most consulting engagements. You can upload years of transcripts, documents, and notes without hitting limits that would affect normal service business use.' },
      { question: 'Does the AI summarize old context or remember specific details?', answer: 'It maintains accessible, searchable memory across all uploaded content. Intelligence surfaces specific details from old documents rather than just high-level summaries.' },
      { question: 'What happens when a client engagement ends?', answer: 'The Workspace and all its data remains in your account. You can archive it for future reference, use it as a handoff document, or delete it. Your choice.' },
      { question: 'Can clients access their own Workspace?', answer: 'Currently, Client Intelligence Workspaces are for your internal use. You control what, if anything, you share with clients from each Workspace.' },
    ],
  },
  {
    slug: 'remove-yourself-from-delivery',
    label: 'Remove Yourself from Delivery',
    h1: 'How to Remove Yourself from Client Delivery Using AI',
    metaDescription: 'If every deliverable requires you personally, you have a job, not a business. Learn how to use Client Intelligence to systematize delivery so you can step back.',
    steps: [
      { step: '1', title: 'Document What You Do in Delivery', body: 'List every repeatable task in your delivery process. Reports, analyses, follow-ups, recommendations. These are the tasks you systematize first using the Account Brain.' },
      { step: '2', title: 'Encode Your Delivery Standards in the Account Brain', body: 'Upload your quality criteria, output templates, and example deliverables. This becomes the standard Intelligence applies when generating deliverables in each client Workspace.' },
      { step: '3', title: 'Assign Skills to Deliverable Types', body: 'Use the 16 Client Intelligence Skills to create workflows for each deliverable type. Intelligence generates the first draft. You define the review criteria and final approval.' },
      { step: '4', title: 'Delegate, Review, and Step Back Further', body: 'Start with Intelligence generating 80% of the deliverable. As quality improves, move to 90%, then 95%. You spend time on the judgment that genuinely requires you.' },
    ],
    scenarios: [
      { title: 'The Indispensable Consultant', story: 'Every deliverable at Kevin firm required his personal review and often his personal creation. He was the bottleneck. His team existed but could not execute without him.', result: 'After building delivery workflows in Client Intelligence, Kevin team runs 80% of deliverables without him. He reviews strategy decisions only. He reclaimed 15 hours per week.' },
      { title: 'The Scale-Ready Agency', story: 'Julia wanted to grow her agency but knew growth would create chaos if every deliverable still ran through her. She needed to systematize before she could add clients.', result: 'Julia encoded her delivery standards in the Account Brain before adding three new clients. Growth went smoothly because Intelligence maintained her standards without requiring her involvement.' },
      { title: 'The Exit-Ready Practice', story: 'When Marcus decided to sell his consulting practice, a broker told him it was worth very little because every client relationship ran through Marcus personally.', result: 'After systematizing delivery in Client Intelligence and running it for six months, Marcus had documented, transferable processes. His valuation increased significantly when he relisted.' },
    ],
    faqs: [
      { question: 'Will clients notice if I am less involved in delivery?', answer: 'If delivery quality stays high or improves, most clients do not notice. Many prefer consistent quality over variable personal involvement. Your Frameworks are still the foundation of every deliverable.' },
      { question: 'What kinds of delivery tasks can AI actually replace?', answer: 'Research, first-draft creation, report formatting, data synthesis, follow-up summaries, template completion, and status updates. Intelligence handles high-volume, repeatable work well.' },
      { question: 'What do I actually keep for myself after systematizing?', answer: 'Strategy judgment, relationship management, and novel problem-solving. The work clients actually pay premium for. The administrative and mechanical delivery work goes to Intelligence.' },
      { question: 'Is this realistic for complex, high-touch consulting?', answer: 'Yes. Even in high-touch work, a significant portion of delivery is repeatable. Systematizing that portion frees your time for the genuinely complex work where your judgment is irreplaceable.' },
    ],
  },
  {
    slug: 'serve-more-clients-same-quality',
    label: 'Serve More Clients Without Losing Quality',
    h1: 'How to Serve More Clients Without Losing Quality',
    metaDescription: 'Scale does not have to mean lower quality. Client Intelligence lets you serve twice as many clients while maintaining or improving delivery standards.',
    steps: [
      { step: '1', title: 'Identify Where Quality Comes From', body: 'Audit your current delivery. Where does quality actually come from? Usually it is Framework application, context retention, and thoroughness. All of which can be systematized in the Account Brain.' },
      { step: '2', title: 'Encode Your Quality Standards', body: 'Upload your quality criteria, review checklists, and example high-quality deliverables. These become the benchmark Intelligence applies in every client Workspace.' },
      { step: '3', title: 'Create Per-Client Workspaces for Personalized Delivery', body: 'Each client Workspace holds their full context and Facts. Quality comes from deeply personalized outputs, not generic deliverables that feel like templates.' },
      { step: '4', title: 'Monitor and Maintain Standards Across All Clients', body: 'Use consistent review checkpoints within each Workspace. Because Intelligence never has bad days, your baseline quality is more consistent than human-only delivery.' },
    ],
    scenarios: [
      { title: 'The Quality Decline Fear', story: 'Sophia had built a reputation on white-glove service. When clients asked if she would scale, she always said no. She did not trust that quality could survive growth.', result: 'After testing Client Intelligence with two new clients, Sophia found her NPS scores were higher than her manually delivered accounts. She added four more clients confidently.' },
      { title: 'The Thin-Margin Growth Problem', story: 'Bernard grew his agency from 8 to 15 clients but margins collapsed because he hired to maintain quality. More revenue, less profit. The growth treadmill.', result: 'By replacing human delivery hours with AI-driven Workspace workflows, Bernard serves 15 clients with the same headcount as 8. Margins are at an all-time high.' },
      { title: 'The Client Who Tested Quality', story: 'A new enterprise client told Claire she would audit deliverable quality across the entire engagement as a condition of renewal. Claire was nervous about scaling simultaneously.', result: 'The client audit found consistency scores above benchmark on every deliverable. The fact that Intelligence applied the same Framework every time was an advantage, not a risk.' },
    ],
    faqs: [
      { question: 'Does scaling always mean lower quality?', answer: 'Only if quality depends entirely on individual human attention that cannot scale. When quality is encoded in Frameworks and applied systematically by Intelligence, it is more consistent at scale than at low volume.' },
      { question: 'How do I handle clients who want personal attention?', answer: 'The high-touch relationship layer stays human. Intelligence handles delivery mechanics, research, and documentation, freeing you for more client interaction, not less.' },
      { question: 'What is a realistic client capacity increase?', answer: 'Most users report 50 to 100% capacity increase within 60 days of full onboarding. The ceiling depends on your specific delivery model and how much of it is systematizable.' },
      { question: 'Will clients notice I am using AI?', answer: 'Clients notice outputs are more consistent and thorough. Whether they associate that with AI depends on whether you tell them. Many users disclose this as a feature, not a secret.' },
    ],
  },
  {
    slug: 'move-ip-from-head-to-ai',
    label: 'Move Your IP from Head to AI',
    h1: 'How to Move Your Expertise from Your Head into an AI System',
    metaDescription: 'If your best thinking only lives in your head, you have a single point of failure. Learn how to extract and encode your expertise into the Account Brain using Brain Dump mode.',
    steps: [
      { step: '1', title: 'Run a Brain Dump Session', body: 'Use Brain Dump mode to capture everything. Voice recordings, rough notes, old slide decks, example deliverables. Get it out of your head and into the Account Brain in any format.' },
      { step: '2', title: 'Let Client Intelligence Organize It into Frameworks', body: 'Upload your raw capture and Client Intelligence structures it into organized, AI-readable Frameworks in the Frameworks library. You refine the structure until it accurately reflects your thinking.' },
      { step: '3', title: 'Test Against Real Scenarios in Client Workspaces', body: 'Run test client scenarios through Intelligence and see if it reasons the way you would. Correct where it diverges. This calibration is how Intelligence learns your judgment.' },
      { step: '4', title: 'Maintain as a Living System', body: 'As your thinking evolves, update your Account Brain. New Frameworks, refined models, and new expertise get added over time. Your IP stays current and deployable.' },
    ],
    scenarios: [
      { title: 'The Single Point of Failure', story: 'When Raj got sick for three weeks, his entire consulting practice ground to a halt. Every deliverable, every decision, every client answer depended on him personally.', result: 'After encoding his expertise in the Account Brain, Raj associate could handle most client work from the documented system during his absence. Nothing stopped.' },
      { title: 'The Retiring Expert', story: 'Carol had 25 years of expertise she wanted to preserve before retiring. A course felt too diluted. A book could not capture the nuance. She needed a live system.', result: 'Carol spent three months encoding her expertise into Client Intelligence. She now licenses access to her Expert Brain as a premium add-on to her advisory retainer. New revenue stream.' },
      { title: 'The Partnership Dissolution', story: 'When Luis business partner left, 40% of the firm expertise walked out the door. They had not documented anything. Rebuilding took two years.', result: 'Luis spent six months encoding all remaining expertise into the Account Brain. If anyone leaves now, the IP stays. He calls it his firm most important insurance policy.' },
    ],
    faqs: [
      { question: 'What if I cannot articulate my Frameworks clearly?', answer: 'Brain Dump mode is designed for this. You do not need polished Frameworks. Just examples, case studies, and rough descriptions of how you think. The Account Brain helps you structure from raw input.' },
      { question: 'How long does a full IP extraction take?', answer: 'Most users reach functional coverage in 4 to 8 hours of focused Brain Dump sessions spread over a few weeks. You can always add more over time. It is not a one-time event.' },
      { question: 'Is my IP protected after uploading?', answer: 'Your IP is isolated in your account and never used to train other users. You own your Frameworks. Client Intelligence is the container, not the owner.' },
      { question: 'Can I share my encoded expertise with my team?', answer: 'Yes. Your Account Brain is accessible to everyone with account access. Your team benefits from your encoded expertise the same way you do, without needing to learn it all from scratch.' },
    ],
  },
  {
    slug: 'scale-coaching-practice',
    label: 'Scale Your Coaching Practice with AI',
    h1: 'How to Scale Your Coaching Practice Without Burning Out',
    metaDescription: 'Coaches who scale without systems burn out. Client Intelligence gives coaching practices per-client Workspaces, consistent Frameworks, and delivery leverage.',
    steps: [
      { step: '1', title: 'Encode Your Coaching Framework in the Account Brain', body: 'Upload your signature coaching methodology, session Frameworks, and diagnostic tools. This becomes the foundation for every client engagement.' },
      { step: '2', title: 'Create a Workspace Per Coaching Client', body: 'Every client gets an isolated Workspace. Session notes, goal tracking, homework, and progress history all live there. Facts are auto-extracted from conversations. Nothing mixes.' },
      { step: '3', title: 'Prepare Sessions Using Intelligence Mode', body: 'Before each session, open the client Workspace. Intelligence surfaces their history, progress, and open questions from their Facts. You arrive fully prepared without manual review.' },
      { step: '4', title: 'Scale Without Compromising Depth', body: 'With session prep handled and notes captured automatically, you have capacity for more clients while maintaining the depth each client expects.' },
    ],
    scenarios: [
      { title: 'The Overbooked Coach', story: 'Maya was maxed at 12 coaching clients and turning away referrals. Each client required so much manual prep and note-taking that she had nothing left after sessions.', result: 'After setting up Client Intelligence Workspaces, Maya handles session prep in minutes instead of an hour. She now coaches 20 clients comfortably and has her evenings back.' },
      { title: 'The Memory Problem', story: 'Jason was embarrassed when he forgot a key detail a coaching client had shared in their third session. The client noticed. The trust was damaged.', result: 'With every session automatically logged and Facts captured in the client Workspace, Jason never forgets anything. He opens each session by asking Intelligence to surface what matters from their history.' },
      { title: 'The Group Program Scale', story: 'Priya ran a group coaching program with 30 participants. Keeping individual context for each person while running group sessions felt impossible.', result: 'Each participant has their own Workspace with their Facts. Priya maintains individual context without the overhead. Group dynamics and individual progress tracking run in parallel.' },
    ],
    faqs: [
      { question: 'Is this designed for executive coaching, life coaching, or business coaching?', answer: 'All three. The Framework-first architecture adapts to any coaching methodology. You encode your specific approach and Intelligence applies it across all your clients.' },
      { question: 'Can AI replace the human connection in coaching?', answer: 'No, and it is not meant to. Intelligence handles the logistics, memory, and documentation so you can spend more session time on the human connection that creates transformation.' },
      { question: 'How do I handle session notes with clients who do not want their data stored?', answer: 'You control what goes into each Workspace. For sensitive clients, you can limit uploads to Framework application and goal tracking without detailed session transcripts.' },
      { question: 'What is the biggest time saving most coaches experience?', answer: 'Session preparation. Coaches typically spend 30 to 60 minutes per client reviewing notes before sessions. Client Intelligence reduces that to 5 minutes by surfacing what matters from the Workspace automatically.' },
    ],
  },
  {
    slug: 'build-leverage-as-consultant',
    label: 'Build Leverage as a Consultant',
    h1: 'How to Build Real Leverage as a Solo Consultant Using AI',
    metaDescription: 'Solo consultants trade time for money by default. Client Intelligence breaks that model by turning your expertise into a scalable system that works across every client.',
    steps: [
      { step: '1', title: 'Define Your Leverage Assets', body: 'Identify what makes you valuable: your Frameworks, your judgment, your relationships. These are the assets to systematize. Time is not an asset. It is a constraint.' },
      { step: '2', title: 'Systematize Your Frameworks in the Account Brain', body: 'Encode your Frameworks into the Account Brain. Now your expertise applies across every client Workspace simultaneously without requiring your presence in each engagement.' },
      { step: '3', title: 'Delegate Execution Tasks to Intelligence', body: 'Route mechanical delivery tasks to Intelligence using the 16 Skills. Research, drafting, formatting, analysis. Your time goes to the judgment and strategy that genuinely requires you.' },
      { step: '4', title: 'Expand Capacity Without Expanding Hours', body: 'With Intelligence handling execution, your effective output per hour increases. You serve more clients, generate more revenue, and work fewer hours. That is leverage.' },
    ],
    scenarios: [
      { title: 'The Time-for-Money Trap', story: 'Alex charged $300 per hour and maxed at 30 billable hours per week. He had built an expensive job, not a business. There was no way to earn more without working more.', result: 'After encoding his Frameworks in the Account Brain and building Workspace workflows, Alex serves 40% more clients without adding hours. He raised his rates because demand exceeded his perceived availability.' },
      { title: 'The IP Monetization Gap', story: 'Theresa had deep expertise worth far more than her hourly rate implied. She could not figure out how to package it for scale without turning it into a course she did not want to teach.', result: 'By encoding her IP in the Account Brain, Theresa now applies it across more clients without the teaching overhead. Her expertise earns at scale without her being in the room.' },
      { title: 'The Vacation Problem', story: 'Sam had not taken a real vacation in four years. Every client needed him directly. Unplugging meant losing business.', result: 'With Client Intelligence systematizing delivery across Workspaces, Sam took 12 days off and clients received timely, quality work. His associate ran most engagements from the documented system.' },
    ],
    faqs: [
      { question: 'What is the difference between leverage and just working faster?', answer: 'Working faster still trades time for output. Leverage means your expertise produces output without requiring proportional time input. The Account Brain systematizes your Frameworks so they apply at scale.' },
      { question: 'Can a solo consultant really build true leverage?', answer: 'Yes, more easily than a larger firm, because you can move fast. The key is systematizing what makes you valuable before you hit your capacity ceiling.' },
      { question: 'Does leverage mean I will work less?', answer: 'It means you choose. Some consultants use leverage to work the same hours and earn more. Others use it to work fewer hours and maintain income. The choice becomes yours.' },
      { question: 'What is the first piece of leverage to build?', answer: 'Framework systematization. Encode your methodology first. This immediately lets you apply your expertise faster and more consistently across all client Workspaces. Measurable leverage from day one.' },
    ],
  },
  {
    slug: 'consistent-client-delivery',
    label: 'Deliver Consistent Client Results at Scale',
    h1: 'How to Deliver Consistent Results to Every Client at Scale',
    metaDescription: 'Consistency is the hardest thing to maintain as you scale. Client Intelligence encodes your standards so every client gets the same quality every time.',
    steps: [
      { step: '1', title: 'Define What Consistent Looks Like', body: 'Document your quality standards, methodology checkpoints, and example high-quality deliverables. This becomes the benchmark Intelligence applies in every client Workspace.' },
      { step: '2', title: 'Encode Standards in Your Account Brain', body: 'Upload your standards, checklists, and examples. Intelligence uses these as the baseline for generating deliverables in every client Workspace, every time.' },
      { step: '3', title: 'Apply Consistently Across All Clients', body: 'Because your standards live in the Account Brain that every client Workspace draws from, the same methodology applies regardless of client size, type, or engagement stage.' },
      { step: '4', title: 'Update Once, Improve Everywhere', body: 'When you find gaps, update your Account Brain. Standards improve system-wide, not just for one client. One update raises quality across every Workspace simultaneously.' },
    ],
    scenarios: [
      { title: 'The Growing Agency Consistency Problem', story: 'Leo agency grew from 5 to 12 clients. As they grew, some clients got great service and others got rushed work. Reviews started reflecting the inconsistency.', result: 'After encoding delivery standards in the Account Brain, every client receives the same methodology and quality benchmark. Negative reviews stopped entirely within 90 days.' },
      { title: 'The Multi-Consultant Divergence', story: 'Rachel three consultants all claimed to follow the same Framework. Client feedback made clear they were delivering very different experiences.', result: 'With the Framework encoded in the Account Brain and all three consultants using the same Workspaces, deliverable consistency improved dramatically. Client feedback became uniformly positive.' },
      { title: 'The High-Stakes Consistency Test', story: 'A Fortune 500 client told Marcus that his firm contract renewal depended on delivering consistent methodology across all 12 of their subsidiary engagements.', result: 'Client Intelligence guaranteed it. Each subsidiary had an isolated Workspace running the same Framework from the Account Brain. The client renewed and expanded the engagement.' },
    ],
    faqs: [
      { question: 'What causes inconsistency in service delivery?', answer: 'Variable context, methodology drift, and human error. Client Intelligence eliminates all three: persistent context via Workspaces, encoded methodology in the Account Brain, and Intelligence that never has bad days.' },
      { question: 'Can AI really maintain my quality standards without my involvement?', answer: 'For Framework application and deliverable generation, yes. Your judgment is still needed for novel situations and strategic decisions. But the structural consistency is solid.' },
      { question: 'What if my quality standards evolve?', answer: 'Update your Account Brain and the improvement applies to all future work across all Workspaces simultaneously. One update improves consistency system-wide.' },
      { question: 'How do I measure whether consistency has actually improved?', answer: 'Track NPS, client feedback themes, repeat purchase rate, and deliverable revision requests. Most users see measurable improvement in these metrics within 60 days.' },
    ],
  },
  {
    slug: 'confidential-ai-for-client-work',
    label: 'Use AI Confidentially for Client Work',
    h1: 'How to Use AI for Client Work Without Risking Confidentiality',
    metaDescription: 'Using general AI tools for confidential client work is a real risk. Client Intelligence provides isolated Workspaces with architectural data separation designed for professional services.',
    steps: [
      { step: '1', title: 'Understand the Risk of General AI Tools', body: 'When you paste client data into ChatGPT or shared AI tools, that data potentially enters training pipelines and exists in shared infrastructure. For confidential work, this is a serious risk.' },
      { step: '2', title: 'Set Up Isolated Workspaces Per Client', body: 'Create a dedicated Workspace for each client. Data you upload is isolated to that Workspace. It does not share infrastructure with other clients or other users.' },
      { step: '3', title: 'Run All Client AI Work Within Their Workspace', body: 'All Intelligence interactions for a client happen inside their Workspace. Facts auto-extracted from conversations stay in that Workspace. Confidentiality is structural, not just policy.' },
      { step: '4', title: 'Maintain a Clean Audit Trail', body: 'Every action within a Workspace is logged to that Workspace. You have a complete record of what was done, when, and with what data. Useful for compliance and client reporting.' },
    ],
    scenarios: [
      { title: 'The Legal Review Blocker', story: 'Emma law firm clients required a legal review of every AI tool she used. ChatGPT failed. Generic AI tools failed. She needed a solution that could survive legal scrutiny.', result: 'Client Intelligence isolated Workspace architecture passed her clients legal reviews. Emma now markets it proactively as a differentiator in professional services RFPs.' },
      { title: 'The Financial Services Compliance Requirement', story: 'Daniel served financial services clients with strict data handling requirements. Using AI was off the table until he could demonstrate structural data isolation.', result: 'Client Intelligence Workspace isolation met his clients compliance requirements. Daniel now uses AI fully for financial services clients who previously prohibited it.' },
      { title: 'The Client Discovery Question', story: 'During a board presentation, a client CTO asked directly: "What AI tools do you use, and how do you handle our data?" This was not a hypothetical question. They needed a clear answer.', result: 'Claire demonstrated Client Intelligence Workspace architecture live. The CTO approved immediately. What could have been a risk became a trust-building moment.' },
    ],
    faqs: [
      { question: 'Is Client Intelligence data used to train AI models?', answer: 'No. Your data and your clients data are not used to train shared models. Your IP and client information stays isolated to your account.' },
      { question: 'Can I share the data handling terms with my clients?', answer: 'Yes. Client Intelligence privacy and data handling documentation is available to share with clients who require review as part of their vendor approval process.' },
      { question: 'What about NDA requirements with clients?', answer: 'Workspace isolation means each client data never interacts with other clients data. For most NDA scenarios, this structure satisfies the information barrier requirements.' },
      { question: 'Is this enterprise-grade security or basic privacy settings?', answer: 'The isolation is architectural, enforced at the data layer, not just via access controls or system prompts. It is designed specifically for professional services confidentiality requirements.' },
    ],
  },
  {
    slug: 'encode-consulting-methodology-ai',
    label: 'Encode Your Methodology in AI',
    h1: 'How to Encode Your Consulting Methodology into an AI System',
    metaDescription: 'Your methodology is your competitive advantage. Learn how to encode it in the Account Brain so it scales with you and never dilutes as your client base grows.',
    steps: [
      { step: '1', title: 'Audit Your Methodology Components', body: 'List every element of your methodology: diagnostic Frameworks, decision trees, output templates, quality criteria, client-specific adaptations. These are what you encode into the Account Brain.' },
      { step: '2', title: 'Organize by Engagement Stage', body: 'Structure your methodology by when it applies: discovery, diagnosis, strategy, implementation, review. This structure makes it easier for Intelligence to apply the right Framework at the right moment.' },
      { step: '3', title: 'Upload in Brain Dump Sessions', body: 'Use Brain Dump mode to capture each component. Do not wait for perfect documentation. Raw thinking, rough notes, and example deliverables all work. Get it in the Account Brain first.' },
      { step: '4', title: 'Validate and Calibrate in Client Workspaces', body: 'Test your encoded methodology against real client scenarios in Workspaces. Refine where Intelligence diverges from how you would approach it. Calibration takes 2 to 4 sessions for most methodologies.' },
    ],
    scenarios: [
      { title: 'The IP Documentation Backlog', story: 'Tom had been meaning to document his methodology for five years. Every attempt stalled because it felt too rigid. Brain Dump mode was the answer.', result: 'By capturing rough thinking rather than polished documentation, Tom had his methodology fully encoded in three weeks. He accomplished in weeks what he had avoided for years.' },
      { title: 'The Methodology Dilution Problem', story: 'As Amara firm grew, her original methodology diluted into generic consulting. New hires did not have her depth and could not encode what they had not internalized.', result: 'Amara encoded her original methodology in the Account Brain before it fully eroded. New hires now operate from the encoded system. The methodology is preserved regardless of individual experience level.' },
      { title: 'The Acquisition Due Diligence', story: 'When a PE firm expressed interest in acquiring Nick consulting practice, their first question was: "How does your methodology get transferred?" Nick had no good answer.', result: 'After encoding his methodology in Client Intelligence, Nick could demonstrate a concrete, transferable IP system in the Account Brain. The methodology was no longer locked in his head. It was an asset.' },
    ],
    faqs: [
      { question: 'How detailed does my methodology need to be before I can encode it?', answer: 'It can be partially formed. Brain Dump mode is designed for iterative capture. You can start with rough Frameworks and refine them over time as Intelligence reveals gaps.' },
      { question: 'What if different clients require different methodologies?', answer: 'Your Account Brain holds multiple methodology variants in the Frameworks library. When working in a client Workspace, you direct Intelligence to apply the relevant variant for that engagement type.' },
      { question: 'Does encoding my methodology make it less flexible?', answer: 'No. The encoded methodology is the foundation, but Intelligence still applies contextual judgment to each client unique situation. Flexibility is preserved through how the Frameworks are framed.' },
      { question: 'Can competitors access my encoded methodology?', answer: 'No. Your Account Brain is isolated to your account and never shared. Your methodology is your IP. Client Intelligence is the secure container, not the owner.' },
    ],
  },
  {
    slug: 'scale-fractional-executive-practice',
    label: 'Scale a Fractional Executive Practice',
    h1: 'How Fractional Executives Use AI to Scale Across Multiple Companies',
    metaDescription: 'Fractional executives serve multiple companies simultaneously. Client Intelligence provides per-company Workspaces, isolated context, and consistent Framework application across every engagement.',
    steps: [
      { step: '1', title: 'Create a Company Workspace for Each Engagement', body: 'Every company you serve gets its own isolated Workspace. Their data, strategy docs, meeting transcripts, and history never mix with your other companies. The isolation is architectural.' },
      { step: '2', title: 'Encode Your Executive Frameworks in the Account Brain', body: 'Upload your playbooks, decision Frameworks, and leadership models. These apply across all company Workspaces as your professional foundation.' },
      { step: '3', title: 'Maintain Deep Context Per Company via Facts', body: 'Every board meeting, strategy session, and 1:1 transcript goes into the company Workspace. Facts auto-extract from conversations. Intelligence always knows the company full history.' },
      { step: '4', title: 'Switch Contexts Without Mental Overhead', body: 'Open a company Workspace before each engagement and Intelligence re-orients you to that company state. No mental overhead from switching between six companies in one week.' },
    ],
    scenarios: [
      { title: 'The Context Switching Burden', story: 'James served six companies as a fractional CFO. Keeping each company context straight in his head was exhausting. He sometimes referenced the wrong company numbers.', result: 'With isolated Workspaces, James switches between companies with zero mental overhead. Intelligence has the full context ready before he needs it. He added two more companies to his roster.' },
      { title: 'The Competing Client Conflict', story: 'Two of Sarah fractional CMO clients were in the same industry. She needed structural data isolation to avoid any possibility of strategic information crossing between them.', result: 'Client Intelligence Workspace isolation gave her the structural separation her NDAs required. Both clients were satisfied with her data handling approach after reviewing the architecture.' },
      { title: 'The Fractional CEO Scale', story: 'Michael wanted to scale his fractional CEO practice beyond three companies but felt three was the limit before quality would suffer.', result: 'With AI-assisted context management and Framework application across Workspaces, Michael serves five companies with better outcomes than when he served three manually.' },
    ],
    faqs: [
      { question: 'How do you handle NDA requirements when serving competing companies?', answer: 'Workspace isolation means data from Company A never enters Company B Workspace. This structural separation satisfies most NDA information barrier requirements for fractional executives.' },
      { question: 'What kinds of documents should go in each company Workspace?', answer: 'Board materials, strategy docs, meeting transcripts, OKRs, financial context, team org charts, and key decision logs. Anything you would reference when working with that company.' },
      { question: 'Can I serve industries with strict data requirements such as healthcare or finance?', answer: 'Yes. The Workspace isolation architecture is designed for professional services data requirements. Many fractional executives in regulated industries use Client Intelligence specifically for this.' },
      { question: 'Does this scale to 10 or more companies?', answer: 'The architecture supports unlimited company Workspaces. Most fractional executives find the cognitive ceiling, not the tool, limits how many they serve effectively, typically 6 to 10 depending on engagement depth.' },
    ],
  },
  {
    slug: 'manage-multiple-client-contexts',
    label: 'Manage Multiple Client Contexts with AI',
    h1: 'How to Manage Multiple Client Contexts Without Confusion or Mix-Up',
    metaDescription: 'Managing context for 10 or more clients simultaneously is cognitively impossible without systems. Client Intelligence provides isolated Workspaces for every client so you never mix up context again.',
    steps: [
      { step: '1', title: 'Isolate Every Client Context in Its Own Workspace', body: 'Each client gets their own Workspace. Context never bleeds between clients. Not in AI outputs, not in document storage, not in conversation history or Facts.' },
      { step: '2', title: 'Build Context Actively Over Time', body: 'Every session, add new information to the client Workspace. Strategy updates, decisions made, issues raised, goals shifted. Facts are auto-extracted. Context grows with every interaction.' },
      { step: '3', title: 'Re-Orient Instantly Before Each Engagement', body: 'Before any client interaction, open their Workspace. Ask Intelligence to surface what matters most: recent decisions, open questions, next steps. Be prepared in minutes.' },
      { step: '4', title: 'Never Lose Context Between Sessions', body: 'Whatever you add to a Workspace persists indefinitely. A client you have not spoken to in three months has full context waiting the moment you need it.' },
    ],
    scenarios: [
      { title: 'The Context Confusion Incident', story: 'Danielle sent a strategy recommendation to Client A that was actually built for Client B. Both companies were in the same sector. The mistake nearly cost her the relationship.', result: 'With isolated Workspaces, Danielle works exclusively within one client context at a time. Cross-client confusion is structurally impossible when Intelligence only has access to that client data.' },
      { title: 'The Long Gap Re-Entry', story: 'Paul had a client who paused their engagement for eight months. When they restarted, Paul had to spend three hours reviewing old notes to get back up to speed.', result: 'After switching to Client Intelligence, Paul opened the client Workspace after the gap and had full context in five minutes. The client was impressed by how prepared he was.' },
      { title: 'The 15-Client Juggle', story: 'Rachel served 15 clients with different industries, stages, and strategies. Keeping track of each one was becoming unsustainable and error-prone.', result: 'Each client Workspace holds their complete context and Facts. Rachel moves between clients throughout the day without mental switching costs. She has not had a context-related error since onboarding.' },
    ],
    faqs: [
      { question: 'What is the maximum number of clients I can realistically manage with this?', answer: 'The tool scales as far as your time allows. Most users with complex client work find 10 to 20 clients is the effective maximum, not because of tool limitations, but because of engagement depth requirements.' },
      { question: 'How do I prevent myself from opening the wrong Workspace?', answer: 'Workspaces are labeled by client name and organized in your dashboard. You select explicitly before interacting. There is no way to accidentally merge context without deliberate action.' },
      { question: 'Can I see a cross-client view anywhere?', answer: 'Your dashboard shows all Workspaces. You can view metadata such as last active and open items across clients for project management purposes. The AI context is always Workspace-specific.' },
      { question: 'Does context include email and call history?', answer: 'Yes if you add it. Upload email threads, call transcripts, and meeting notes to the Workspace. Facts are auto-extracted. Intelligence can surface and reason from all of it.' },
    ],
  },
  {
    slug: 'turn-framework-into-ai-agent',
    label: 'Turn Your Framework into an AI Agent',
    h1: 'How to Turn Your Consulting Framework into a Working AI Agent',
    metaDescription: 'Your Frameworks are the most valuable thing you own as a consultant. Learn how to encode them in the Account Brain so they work as intelligent agents delivering your thinking at scale.',
    steps: [
      { step: '1', title: 'Document Your Framework as Decision Logic', body: 'Reframe your Framework as a series of decisions. What data do I gather first? What questions do I ask? What does each answer tell me? What actions follow? This becomes the agent logic.' },
      { step: '2', title: 'Encode the Logic in Your Account Brain', body: 'Upload your decision Framework in structured form using Brain Dump mode. Include diagnostic questions, decision criteria, and output formats for each scenario.' },
      { step: '3', title: 'Attach Skills to Framework Stages', body: 'Use the 16 Client Intelligence Skills to attach specific AI capabilities to specific stages of your Framework. Research for diagnosis, drafting for recommendations, analysis for review.' },
      { step: '4', title: 'Run Your Framework Agent in Client Workspaces', body: 'Deploy your Framework agent within each client Workspace. It has access to that client context and your methodology simultaneously. Personalized and systematized at once.' },
    ],
    scenarios: [
      { title: 'The Expert-in-a-Box Vision', story: 'Priya had built a diagnostic Framework for identifying conversion problems that consultants spent months learning. She wanted to encode it so junior team members could run it.', result: 'After encoding her Framework in the Account Brain, junior team members produce diagnostic outputs as accurate as Priya own. She has multiplied her expertise across her team.' },
      { title: 'The Due Diligence Framework', story: 'Marcus ran acquisition due diligence for PE clients. Every deal required applying a 40-point Framework manually. It was consistent but slow.', result: 'His due diligence Framework now runs as an agent in Client Intelligence Workspaces. He applies it to each deal in hours instead of weeks. He took on three more deals last quarter.' },
      { title: 'The Repeatable Growth Playbook', story: 'Oliver had a growth playbook that worked for SaaS businesses at specific stages. He ran it manually for clients. It was excellent, but only he could run it.', result: 'After encoding it in the Account Brain, Oliver associate applies the playbook accurately in client Workspaces. Oliver focuses on client relationships and novel strategy while the playbook executes.' },
    ],
    faqs: [
      { question: 'Is there a difference between encoding a Framework and building an agent?', answer: 'An encoded Framework is passive. You apply it. An agent uses it to take actions and generate outputs. Client Intelligence Skills system lets you move from passive encoding to active agent behavior.' },
      { question: 'Do I need technical expertise to build an agent?', answer: 'No coding required. You describe your Framework logic in natural language and Client Intelligence structures it into agent behavior. The system is designed for experts, not engineers.' },
      { question: 'Can my Framework agent learn and improve over time?', answer: 'As you refine your Account Brain by adding new examples, correcting edge cases, and updating decision logic, your Framework agent improves for all future client applications.' },
      { question: 'What kinds of Frameworks work best as agents?', answer: 'Diagnostic Frameworks, scoring models, research workflows, and multi-step assessment processes are ideal. Any Framework with clear steps and criteria is highly agentizable.' },
    ],
  },
  {
    slug: 'scale-revops-consulting',
    label: 'Scale RevOps Consulting with AI',
    h1: 'How RevOps Consultants Use AI to Scale Client Delivery',
    metaDescription: 'RevOps consultants manage complex multi-system client environments. Client Intelligence provides per-client Workspaces, consistent Frameworks, and scalable delivery across your book of business.',
    steps: [
      { step: '1', title: 'Encode Your RevOps Frameworks in the Account Brain', body: 'Upload your revenue operations playbooks, audit Frameworks, and optimization models. These become the consistent methodology across all client engagements.' },
      { step: '2', title: 'Create Client-Specific Workspaces', body: 'Each client Workspace holds their CRM structure, process maps, audit findings, and strategy documents. Isolated context for complex multi-tool environments.' },
      { step: '3', title: 'Run Diagnostic Work Through Intelligence Mode', body: 'Apply your RevOps audit Framework to each client context. Intelligence generates the analysis while you focus on interpretation and strategy.' },
      { step: '4', title: 'Scale Across More Clients', body: 'With Intelligence handling diagnostic and documentation work using the 16 Skills, you serve more clients without the quality drop that comes from stretching your time.' },
    ],
    scenarios: [
      { title: 'The Complex Multi-Client RevOps Practice', story: 'Elena served eight RevOps clients across different CRMs, sales motions, and tech stacks. Keeping each client context separate while applying consistent Frameworks was a constant challenge.', result: 'With isolated Workspaces per client and shared Frameworks in the Account Brain, Elena applies RevOps best practices consistently while tracking each client unique configuration.' },
      { title: 'The Audit Documentation Bottleneck', story: 'Marcus RevOps audits were thorough but documentation took twice as long as the analysis. He was billing for documentation time clients did not value.', result: 'After running audit documentation through Client Intelligence Skills, Marcus produces the same documentation in a quarter of the time. He reduced documentation hours and increased his client count.' },
      { title: 'The Framework Inconsistency Across Engagements', story: 'As Jake RevOps consultancy grew, different consultants applied their Frameworks differently. Client outcomes varied in ways that were embarrassing when compared in reference calls.', result: 'With their Frameworks encoded in the Account Brain, all consultants apply the same methodology in every Workspace. Client outcomes are now consistently citable in reference conversations.' },
    ],
    faqs: [
      { question: 'Can Client Intelligence integrate with CRM systems directly?', answer: 'Client Intelligence integrates with Google Drive, Notion, Slack, GitHub, Zoom, and Gmail. You can add CRM exports and process documentation to Workspaces. Direct CRM integrations continue to expand.' },
      { question: 'Is this useful for RevOps advisory or only for implementation consulting?', answer: 'Both. For advisory, the Framework application and diagnostics work is the core use case. For implementation consulting, the project management and documentation workflows add significant efficiency.' },
      { question: 'How do you handle client data that is commercially sensitive?', answer: 'Each client Workspace is isolated. Revenue data, pipeline data, and process documentation for Client A never appears in Client B Workspace. The isolation is architectural.' },
      { question: 'Can I use this to onboard clients faster?', answer: 'Yes. Upload your onboarding questionnaire outputs and initial audit findings to the Workspace immediately. Intelligence has full context from the start of the engagement.' },
    ],
  },
  {
    slug: 'ai-for-high-ticket-delivery',
    label: 'AI for High-Ticket Service Delivery',
    h1: 'How to Use AI to Scale High-Ticket Service Delivery',
    metaDescription: 'High-ticket clients expect personalization and depth. Client Intelligence gives you per-client AI memory and Framework application so you deliver premium service at scale.',
    steps: [
      { step: '1', title: 'Build Deep Client Context in Their Workspace', body: 'High-ticket clients expect you to know them deeply. Upload every relevant detail, their business model, goals, history, preferences, and past interactions. Facts auto-extract from conversations.' },
      { step: '2', title: 'Apply Premium Frameworks from the Account Brain', body: 'Your high-ticket methodology lives in the Account Brain. Every deliverable starts from your best Frameworks, not generic templates. Every client feels the difference.' },
      { step: '3', title: 'Generate Personalized, Thorough Deliverables', body: 'Because Intelligence has both your Frameworks and the client specific context, outputs are deeply personalized. High-ticket clients notice the depth and attribute it to your expertise.' },
      { step: '4', title: 'Scale Premium Without Diluting It', body: 'Add high-ticket clients without dropping quality. Intelligence handles systematic work using the 16 Skills. You handle the relationship and strategic judgment that justifies premium pricing.' },
    ],
    scenarios: [
      { title: 'The Premium Consistency Problem', story: 'Claire charged $25k per engagement. When she served five clients simultaneously, some received more of her attention than others. Premium clients noticed the inconsistency.', result: 'With Client Intelligence applying her Frameworks consistently across all five client Workspaces, every deliverable reflects her premium methodology. All five clients feel like her main client.' },
      { title: 'The High-Ticket Referral Growth', story: 'Sam high-ticket coaching practice grew through referrals but he could not take them without worrying about capacity. He had turned down four referrals in a year.', result: 'By building AI-assisted delivery workflows in Workspaces, Sam added three new high-ticket clients without compromising quality for existing ones. He stopped turning away referrals.' },
      { title: 'The Premium Justification Pressure', story: 'A prospect challenged David on why his $30k methodology engagement was worth it versus cheaper alternatives. He needed a compelling answer to "what do I actually get?"', result: 'David now demonstrates Client Intelligence as part of his sales process, showing prospects the depth of context, personalized Framework application, and thoroughness they will receive. Conversion increased.' },
    ],
    faqs: [
      { question: 'Do high-ticket clients expect everything to come from you personally?', answer: 'They expect the quality and depth that comes from your expertise. Intelligence delivers your Frameworks and applies your methodology, which is what they are actually buying, with more consistency than you can manually.' },
      { question: 'Will using AI affect how I can position my high-ticket offer?', answer: 'It strengthens the position. You can now deliver more depth, more consistency, and more personalization than hand-crafted solo delivery allows. That is a premium argument, not a discount.' },
      { question: 'How do I maintain the human relationship layer at premium tier?', answer: 'Intelligence handles systematic work so you have more time for relationship-building, strategic sessions, and executive presence. The human elements that premium clients value most.' },
      { question: 'Can I serve multiple high-ticket clients simultaneously?', answer: 'Yes. Client Intelligence Workspaces are your internal delivery tool. What clients experience is excellent, consistent, personalized service backed by your Frameworks applied at scale.' },
    ],
  },
  {
    slug: 'build-one-person-agency-with-ai',
    label: 'Build a One-Person Agency with AI',
    h1: 'How to Build a One-Person Agency That Runs Like a Full Team',
    metaDescription: 'One-person agencies are limited by the founder time. Client Intelligence systematizes delivery, context management, and Framework application so you operate like a full team.',
    steps: [
      { step: '1', title: 'Map Every Agency Function', body: 'List everything a full agency does: strategy, research, copywriting, project management, quality review, client communication. These are your systematization targets.' },
      { step: '2', title: 'Encode Agency Standards and Processes in the Account Brain', body: 'Upload your quality standards, delivery SOPs, client communication templates, and Framework documents. This is your agency operating system.' },
      { step: '3', title: 'Create Workspaces as Agency Accounts', body: 'Each client gets a Workspace that functions like a full account within your one-person agency. Complete context, isolated data, Facts captured automatically, and consistent delivery processes.' },
      { step: '4', title: 'Run Agency-Level Output Using the 16 Skills', body: 'With Intelligence handling research, drafting, formatting, and documentation using the 16 Skills, you produce agency-level output volume and quality as a solo operator.' },
    ],
    scenarios: [
      { title: 'The Solo Operator Ceiling', story: 'Amanda had built a great one-person marketing agency but was maxed at six clients. Every client required direct involvement in every deliverable. She could not grow without hiring.', result: 'After systematizing her agency processes in Client Intelligence, Amanda serves nine clients while maintaining quality. She generates more revenue as a solo operator than most small agencies with teams.' },
      { title: 'The Hiring Hesitation', story: 'Ryan kept almost hiring but held back. He did not want management overhead and was not sure the revenue justified the risk. He needed agency-level capacity without agency-level headcount.', result: 'Client Intelligence gave Ryan the capacity increase he needed without an employee. His margins stayed high and he avoided the management complexity that was killing his enjoyment of the work.' },
      { title: 'The Agency Quality Pitch', story: 'A prospect asked Mei how her one-person operation could compete with agencies that had five-person teams. She needed a credible answer.', result: 'Mei demonstrates that her AI-systematized delivery produces more consistent and thorough work than multi-person agencies where quality varies by who is assigned. Three prospects chose her over full agencies.' },
    ],
    faqs: [
      { question: 'Can a one-person agency really compete with full agencies on quality?', answer: 'Yes, often exceeding them. Full agencies have quality variation across team members. A one-person agency with AI systematization has consistent quality, singular focus, and no account hand-offs.' },
      { question: 'What agency functions are most improved by Client Intelligence?', answer: 'Research, strategy documentation, deliverable creation, client reporting, and project tracking. These high-volume, repeatable functions are where Intelligence delivers the most capacity.' },
      { question: 'Is there a point where I have to hire anyway?', answer: 'That depends on your revenue goal and service model. Many one-person agencies with Client Intelligence comfortably serve 10 to 15 clients solo. Beyond that, hiring becomes a choice rather than a requirement.' },
      { question: 'How do I position this to clients who ask about my team size?', answer: 'Honestly. Emphasize that they get consistent senior attention on every deliverable rather than being assigned a junior account manager. Frame solo-plus-AI as a premium model, not a limitation.' },
    ],
  },
  {
    slug: 'ai-knowledge-management-consultants',
    label: 'AI Knowledge Management for Consultants',
    h1: 'How Consultants Use AI for Knowledge Management and Client Delivery',
    metaDescription: 'Consultants generate enormous amounts of valuable knowledge. Client Intelligence provides a permanent, searchable Account Brain for your entire practice.',
    steps: [
      { step: '1', title: 'Centralize All Practice Knowledge in the Account Brain', body: 'Upload Frameworks, case studies, methodologies, research, templates, and institutional knowledge. This becomes your practice permanent Brain, accessible in every client Workspace.' },
      { step: '2', title: 'Make Knowledge Accessible in Every Client Workspace', body: 'When working in any client Workspace, Intelligence draws from your Account Brain to apply relevant knowledge to that client situation. No manual search required.' },
      { step: '3', title: 'Keep Knowledge Current', body: 'As you complete engagements, add learnings, refined Frameworks, and new case studies to the Account Brain. Your Brain grows with your practice and becomes more valuable over time.' },
      { step: '4', title: 'Deploy Knowledge at the Speed of Intelligence', body: 'What used to require manual research through your files now surfaces in seconds. Intelligence knows your Account Brain and applies it in context during every session.' },
    ],
    scenarios: [
      { title: 'The Lost Knowledge Problem', story: 'After ten years, Rachel had an enormous body of knowledge in emails, drive folders, and her head. Useful insights were constantly buried and rediscovered too late or not at all.', result: 'After uploading her full knowledge library to the Account Brain, Rachel surfaces relevant insights during client engagements in real-time. She is mining knowledge she had forgotten she had.' },
      { title: 'The Institutional Knowledge Risk', story: 'When a senior consultant at David firm left, significant institutional knowledge left with them. The remaining team did not know what they had lost until they needed it.', result: 'David now systematically uploads all knowledge created by his team into the Account Brain. If anyone leaves, the knowledge stays. The firm intellectual capital belongs to the firm.' },
      { title: 'The Case Study Application Gap', story: 'Marcus had case studies from 30 engagements. They were in a folder no one consulted. When relevant precedents existed, his team did not know to look.', result: 'With case studies in the Account Brain, Intelligence surfaces relevant precedents automatically when working in Workspaces. Institutional knowledge is now actively used, not passively stored.' },
    ],
    faqs: [
      { question: 'How is this different from a shared drive or wiki?', answer: 'A shared drive requires you to search. Client Intelligence surfaces relevant knowledge automatically based on context: what you are working on, which client, and what questions you are asking.' },
      { question: 'What is the best way to organize knowledge for AI access?', answer: 'Less structure is needed than you would think. Upload in any format and Client Intelligence handles organization. Clear naming and occasional tagging helps, but perfect taxonomy is not required.' },
      { question: 'Can multiple consultants contribute to the same Account Brain?', answer: 'Yes. Everyone with account access can add to the Account Brain. Knowledge contributed by any team member is accessible to all, building collective institutional intelligence.' },
      { question: 'Does old knowledge become irrelevant and clutter the system?', answer: 'You can archive or delete outdated content. But most historical knowledge remains useful. Past case studies, old Frameworks, and previous analyses often surface unexpected relevance years later.' },
    ],
  },
  {
    slug: 'protect-client-data-in-ai',
    label: 'Protect Client Data in AI Systems',
    h1: 'How to Protect Client Data When Using AI Across Multiple Engagements',
    metaDescription: 'Using AI for multiple clients without data isolation is a serious risk. Learn how Client Intelligence Workspace architecture protects every client data structurally.',
    steps: [
      { step: '1', title: 'Audit Your Current AI Data Exposure', body: 'Review how you currently use AI for client work. If client data goes into shared AI tools like ChatGPT, it potentially exists in shared infrastructure. Understand your current exposure before it becomes a problem.' },
      { step: '2', title: 'Move to Isolated Workspaces Per Client', body: 'Create a dedicated Client Intelligence Workspace for each client. All client data you upload is isolated to that Workspace, structurally separated from all other clients.' },
      { step: '3', title: 'Establish Data Entry Protocols', body: 'Decide what types of data go into each Workspace and document your protocol. Consistent data handling lets you make accurate claims about your data practices to clients.' },
      { step: '4', title: 'Maintain Clean Documentation via Session History', body: 'Every upload and action in a Workspace is logged there. You have a complete audit trail for each client. Useful for compliance, disputes, or demonstrating professionalism.' },
    ],
    scenarios: [
      { title: 'The Contract Risk Discovery', story: 'During a legal review, Tom attorney flagged that his current AI tool usage likely violated the data handling clauses in three client contracts. He had 30 days to fix it.', result: 'Tom migrated all client work to Client Intelligence Workspaces within the deadline. The structural isolation satisfied his attorneys and he renewed all three contracts without penalty.' },
      { title: 'The GDPR Compliance Requirement', story: 'Two of Maria clients were EU-based with GDPR requirements that included data isolation obligations. Her current AI workflow could not demonstrate compliance.', result: 'Client Intelligence Workspace isolation provided the architectural separation GDPR required. Maria documented the data flow and her EU clients legal teams approved the tool.' },
      { title: 'The Proactive Protection Play', story: 'Before a client asked about data handling, Claire decided to get ahead of the question. She switched to Client Intelligence and updated her service agreements to reflect proper data handling.', result: 'Three months later, a major prospect asked specifically about data handling during contract negotiations. Claire proactive approach closed the deal. The prospect had passed on competitors who could not answer clearly.' },
    ],
    faqs: [
      { question: 'What specific data risks does Workspace isolation address?', answer: 'Cross-client contamination (one client data appearing in another outputs), data pooling in shared AI training, and unauthorized access. Isolation addresses all three structurally.' },
      { question: 'Is Client Intelligence GDPR compliant?', answer: 'Data processing agreements and compliance documentation are available. For specific GDPR questions, review the privacy documentation or contact Client Intelligence directly. Requirements vary by use case.' },
      { question: 'What should I tell clients about my AI usage?', answer: 'Most clients appreciate transparency. Explaining that you use Client Intelligence with isolated Workspaces per client typically increases trust rather than creating concern.' },
      { question: 'Can I demonstrate data isolation to skeptical clients?', answer: 'Yes. The Workspace architecture can be explained and demonstrated. The structural nature of the isolation, not just policy-based, tends to satisfy technically sophisticated clients.' },
    ],
  },
  {
    slug: 'scale-agency-delivery-without-growing-team',
    label: 'Scale Agency Delivery Without Growing Your Team',
    h1: 'How to Scale Your Agency Delivery Without Growing Your Team',
    metaDescription: 'Every new client should not require a new hire. Client Intelligence lets agencies scale delivery capacity without adding headcount by systematizing Frameworks and handling repeatable work.',
    steps: [
      { step: '1', title: 'Audit Where Delivery Time Goes', body: 'Track how your team spends delivery time across all clients. Most agencies find 40 to 60% is research, drafting, formatting, and documentation. All systematizable in Client Intelligence.' },
      { step: '2', title: 'Systematize Repeatable Delivery Work Using Skills', body: 'Use the 16 Client Intelligence Skills to build workflows for the repeatable deliverables your agency produces across clients: reports, strategies, analyses, presentations.' },
      { step: '3', title: 'Maintain Per-Client Quality With Workspace Isolation', body: 'Each client Workspace ensures your systematized delivery produces personalized, contextually appropriate outputs from that client Facts and history, not generic content that feels templated.' },
      { step: '4', title: 'Scale Headcount-to-Client Ratio', body: 'With Intelligence handling systematic delivery tasks, each team member serves more clients at the same quality level. Revenue grows without proportional headcount increase.' },
    ],
    scenarios: [
      { title: 'The Headcount Ceiling', story: 'Every time Diego agency won two new clients, he had to hire another person. Margins were constant but the management complexity compounded. Growth was eating him alive.', result: 'After systematizing delivery in Client Intelligence, Diego existing team serves 30% more clients. He has not hired in eight months and margin has increased for the first time in three years.' },
      { title: 'The Junior Staff Quality Gap', story: 'Natasha agency relied on junior staff to deliver, but quality was inconsistent. She spent enormous time reviewing and correcting work that missed her standards.', result: 'With her standards encoded in the Account Brain, junior staff produce within her quality range from the first draft. Review time dropped by 60% and client satisfaction improved.' },
      { title: 'The Rapid Growth Scare', story: 'When Felix agency landed a large contract that doubled their client count overnight, he panicked. He could not hire fast enough to maintain quality.', result: 'By deploying Client Intelligence Workspaces and Skills workflows across all new clients immediately, Felix team absorbed the growth without a quality drop. He did not make a single emergency hire.' },
    ],
    faqs: [
      { question: 'How much can I realistically scale before needing to hire?', answer: 'Most agencies report being able to add 30 to 50% more clients before needing additional headcount. The exact multiplier depends on how much of your delivery is systematizable.' },
      { question: 'Will clients notice if their work is partly AI-generated?', answer: 'Clients notice quality and consistency. When Intelligence maintains your standards and applies client-specific context from their Workspace, outputs feel personal and premium.' },
      { question: 'How do I convince my existing team to change their workflow?', answer: 'Show them it reduces their repetitive work, not their job security. Most agency staff embrace Intelligence when they see it eliminates the documentation and formatting tasks they dislike most.' },
      { question: 'What happens to the humans on my team if AI does more of the work?', answer: 'They move up the value chain. From research to strategy, from execution to direction, from task to relationship. Intelligence handles mechanical work. Humans handle judgment and client relationships.' },
    ],
  },
  {
    slug: 'systematize-expert-knowledge-ai',
    label: 'Systematize Expert Knowledge with AI',
    h1: 'How to Systematize Your Expert Knowledge Using AI',
    metaDescription: 'Expert knowledge locked in your head is a liability. Client Intelligence helps you extract, structure, and deploy your expertise across every client engagement through the Account Brain.',
    steps: [
      { step: '1', title: 'Extract Knowledge from Your Head Using Brain Dump Mode', body: 'Use Brain Dump mode to capture everything. Voice memos, rough notes, example outputs, case study details, decision Frameworks. Do not wait for it to be organized. Get it out first.' },
      { step: '2', title: 'Structure It into Deployable Frameworks', body: 'Client Intelligence organizes your raw knowledge into structured, AI-readable Frameworks in the Frameworks library. You refine the structure until it accurately represents how you actually think and decide.' },
      { step: '3', title: 'Test Against Real Client Problems in Workspaces', body: 'Run actual client challenges through your systematized knowledge in client Workspaces. Does Intelligence reason the way you would? Calibrate until outputs match your expert judgment.' },
      { step: '4', title: 'Deploy and Improve Continuously', body: 'Your systematized knowledge applies to every client engagement. As you refine the Account Brain with new cases and insights, it gets more precise. Expert knowledge compounds when systematized.' },
    ],
    scenarios: [
      { title: 'The Inarticulate Expert', story: 'Brian was brilliant at diagnosing client problems but could not explain his process. He just knew. Systematizing felt impossible because the knowledge was intuitive.', result: 'Brain Dump mode captured Brian intuitive process through examples and case walkthroughs instead of abstract Frameworks. His implicit knowledge became explicit and deployable in every Workspace.' },
      { title: 'The Knowledge Silo Problem', story: 'Aisha three-person consulting firm had three experts who each knew different things. Knowledge transfer between them was slow, incomplete, and dependent on individual availability.', result: 'Each expert uploaded their domain knowledge to the Account Brain. Now all three draw from the collective Brain in every client Workspace. Cross-domain application improved immediately.' },
      { title: 'The Succession Readiness Challenge', story: 'When Paul business partner announced he was retiring in 18 months, Paul realized that 40% of the firm expertise would walk out with him.', result: 'The retiring partner spent 12 months systematizing his knowledge in Client Intelligence. When he left, the IP stayed. The firm maintained the Brain he had spent 20 years building.' },
    ],
    faqs: [
      { question: 'What if I cannot articulate my knowledge clearly?', answer: 'That is what Brain Dump mode is for. Start with examples: case studies, past decisions, and descriptions of what you would do in a given situation. The Account Brain helps structure implicit knowledge from concrete examples.' },
      { question: 'Is systematizing knowledge the same as making it generic?', answer: 'No. Systematized knowledge is still your specific Frameworks, applied to each client specific context. It is the opposite of generic. It is your expertise made more accessible and consistent.' },
      { question: 'How do I know when I have captured enough?', answer: 'When Intelligence outputs in test scenarios feel like you wrote them, you have captured enough for current deployment. You can always continue adding depth over time.' },
      { question: 'Will competitors benefit from me systematizing my knowledge?', answer: 'No. Your knowledge is isolated in your Client Intelligence account. It is never shared with other users or used for any purpose outside your account. Systematizing protects your IP by making it explicit.' },
    ],
  },
  {
    slug: 'per-client-ai-memory-setup',
    label: 'Set Up Per-Client AI Memory',
    h1: 'How to Set Up Per-Client AI Memory for Your Service Business',
    metaDescription: 'AI without per-client memory treats every session like the first. Learn how to set up persistent, isolated AI memory for every client using Client Intelligence Workspaces.',
    steps: [
      { step: '1', title: 'Create a Workspace for Each Client', body: 'Log in to Client Intelligence and create a new Workspace for each active client. Name them clearly. This is the container for everything Intelligence will remember about that client.' },
      { step: '2', title: 'Populate Initial Client Memory', body: 'Upload the client onboarding information: their goals, challenges, business context, key stakeholders, and any prior work history. This seeds the AI memory in the Workspace.' },
      { step: '3', title: 'Let Facts Auto-Extract After Every Interaction', body: 'Client Intelligence automatically extracts Facts from conversations and logs them to the client Workspace. Key details are captured without requiring manual note-taking after every session.' },
      { step: '4', title: 'Use Memory to Prepare and Deliver', body: 'Before each client interaction, open their Workspace and ask Intelligence to surface what matters. After each interaction, add new information. Memory compounds over time.' },
    ],
    scenarios: [
      { title: 'The Memory Reset Frustration', story: 'Every AI session, Linda started by re-explaining each client situation. With twelve clients, she spent 30 minutes per week just priming AI with context she had already captured.', result: 'After setting up per-client Workspaces in Client Intelligence, context is permanent. She opens a Workspace and Intelligence already knows the client full history. That time is gone.' },
      { title: 'The Long-Engagement Context Value', story: 'Alex had worked with one client for 14 months. The depth of context he had accumulated was enormous and priceless for delivering relevant advice. It lived in scattered notes.', result: 'After loading 14 months of engagement history into a Client Intelligence Workspace, Alex surfaces any past decision instantly. Long-term clients notice he references history they had forgotten sharing.' },
      { title: 'The Handoff Quality Improvement', story: 'When Mei agency assigned a new account manager to a client, the transition always had a two-week getting-up-to-speed lag that clients hated.', result: 'With Workspaces containing full engagement history and auto-captured Facts, new account managers are operational in hours. Clients report the handoff as seamless, a first for the agency.' },
    ],
    faqs: [
      { question: 'How much information should I put in each client initial memory?', answer: 'Start with the essentials: goals, current challenges, business context, key relationships, and any prior work. You can add depth over time. A 20-minute Brain Dump session per client is enough to start.' },
      { question: 'Does memory degrade or need to be refreshed?', answer: 'Memory persists permanently in the Workspace. It does not degrade or expire. You only update it when the client situation changes or you add new information.' },
      { question: 'Can I set up Workspaces before the first client session?', answer: 'Yes. Create the Workspace and upload whatever you know about the prospect before the engagement begins. Starting with context is a strong first impression.' },
      { question: 'How is per-client AI memory different from just keeping good notes?', answer: 'Notes require you to search and manually apply. Per-client AI memory is actively referenced by Intelligence when generating outputs. It automatically surfaces relevant history in context without you having to search.' },
    ],
  },
]
